
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Errors - Node.js 8 LTS - W3cubDocs</title>
  
  <meta name="description" content=" Applications running in Node.js will generally experience four categories of errors&#58; ">
  <meta name="keywords" content="errors, -, node, js, lts, node~8_lts">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="http://docs.w3cub.com/node~8_lts/errors/">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" integrity="sha256-6/DH7X+2hvUPElJfGsvzm+tgIpmM9zjbYxnpsr6gR1A=" crossorigin="anonymous" href="/assets/application-ebf0c7ed7fb686f50f12525f1acbf39beb6022998cf738db6319e9b2bea04750.css">
  <script type="text/javascript" src="/assets/application-db285287b40ed28fac520fcfd75d7d874692b647b5b5e05968c741dda5de4148.js" integrity="sha256-2yhSh7QO0o+sUg/P1119h0aStke1teBZaMdB3aXeQUg=" crossorigin="anonymous"></script>
  <script src="/json/node~8_lts.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-2572770204602497",
            enable_page_level_ads: true
        });
  </script>
  <script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body>
	<div class="_app">
	<header class="_header">
  
  <form class="_search">
    <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
    <a class="_search-clear"></a>
    <div class="_search-tag"></div>
  </form>
  
  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/node~8_lts/" class="_nav-link" title="" style="margin-left:0;">Node.js 8 LTS</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		<div class="_list">
			
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="link"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _node">
				
				
<h1 id="errors_errors">Errors</h1>   <p>Applications running in Node.js will generally experience four categories of errors:</p> <ul> <li>Standard JavaScript errors such as:<ul> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError" class="type" target="_blank">&lt;EvalError&gt;</a> : thrown when a call to <code>eval()</code> fails.</li> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError" class="type" target="_blank">&lt;SyntaxError&gt;</a> : thrown in response to improper JavaScript language syntax.</li> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError" class="type" target="_blank">&lt;RangeError&gt;</a> : thrown when a value is not within an expected range</li> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError" class="type" target="_blank">&lt;ReferenceError&gt;</a> : thrown when using undefined variables</li> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError" class="type" target="_blank">&lt;TypeError&gt;</a> : thrown when passing arguments of the wrong type</li> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError" class="type" target="_blank">&lt;URIError&gt;</a> : thrown when a global URI handling function is misused.</li> </ul> </li> <li>System errors triggered by underlying operating system constraints such as attempting to open a file that does not exist, attempting to send data over a closed socket, etc;</li> <li>And User-specified errors triggered by application code.</li> <li>Assertion Errors are a special class of error that can be triggered whenever Node.js detects an exceptional logic violation that should never occur. These are raised typically by the <code>assert</code> module.</li> </ul> <p>All JavaScript and System errors raised by Node.js inherit from, or are instances of, the standard JavaScript <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error" class="type" target="_blank">&lt;Error&gt;</a> class and are guaranteed to provide <em>at least</em> the properties available on that class.</p> <h2 id="errors_error_propagation_and_interception">Error Propagation and Interception</h2>  <p>Node.js supports several mechanisms for propagating and handling errors that occur while an application is running. How these errors are reported and handled depends entirely on the type of Error and the style of the API that is called.</p> <p>All JavaScript errors are handled as exceptions that <em>immediately</em> generate and throw an error using the standard JavaScript <code>throw</code> mechanism. These are handled using the <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch" target="_blank"><code>try / catch</code> construct</a> provided by the JavaScript language.</p> <pre data-language="js">// Throws with a ReferenceError because z is undefined
try {
  const m = 1;
  const n = m + z;
} catch (err) {
  // Handle the error here.
}
</pre> <p>Any use of the JavaScript <code>throw</code> mechanism will raise an exception that <em>must</em> be handled using <code>try / catch</code> or the Node.js process will exit immediately.</p> <p>With few exceptions, <em>Synchronous</em> APIs (any blocking method that does not accept a <code>callback</code> function, such as <a href="../fs/#fs_fs_readfilesync_path_options"><code>fs.readFileSync</code></a>), will use <code>throw</code> to report errors.</p> <p>Errors that occur within <em>Asynchronous APIs</em> may be reported in multiple ways:</p> <ul> <li>Most asynchronous methods that accept a <code>callback</code> function will accept an <code>Error</code> object passed as the first argument to that function. If that first argument is not <code>null</code> and is an instance of <code>Error</code>, then an error occurred that should be handled.</li> </ul>  <pre data-language="js">  const fs = require('fs');
  fs.readFile('a file that does not exist', (err, data) =&gt; {
    if (err) {
      console.error('There was an error reading the file!', err);
      return;
    }
    // Otherwise handle the data
  });
</pre> <ul> <li>
<p>When an asynchronous method is called on an object that is an <code>EventEmitter</code>, errors can be routed to that object's <code>'error'</code> event.</p> <pre data-language="js">const net = require('net');
const connection = net.connect('localhost');

// Adding an 'error' event handler to a stream:
connection.on('error', (err) =&gt; {
  // If the connection is reset by the server, or if it can't
  // connect at all, or on any sort of error encountered by
  // the connection, the error will be sent here.
  console.error(err);
});

connection.pipe(process.stdout);
</pre> </li> <li>
<p>A handful of typically asynchronous methods in the Node.js API may still use the <code>throw</code> mechanism to raise exceptions that must be handled using <code>try / catch</code>. There is no comprehensive list of such methods; please refer to the documentation of each method to determine the appropriate error handling mechanism required.</p> </li> </ul> <p>The use of the <code>'error'</code> event mechanism is most common for <a href="../stream/">stream-based</a> and <a href="../events/#events_class_eventemitter">event emitter-based</a> APIs, which themselves represent a series of asynchronous operations over time (as opposed to a single operation that may pass or fail).</p> <p>For <em>all</em> <code>EventEmitter</code> objects, if an <code>'error'</code> event handler is not provided, the error will be thrown, causing the Node.js process to report an unhandled exception and crash unless either: The <a href="../domain/"><code>domain</code></a> module is used appropriately or a handler has been registered for the <a href="../process/#process_event_uncaughtexception"><code>process.on('uncaughtException')</code></a> event.</p> <pre data-language="js">const EventEmitter = require('events');
const ee = new EventEmitter();

setImmediate(() =&gt; {
  // This will crash the process because no 'error' event
  // handler has been added.
  ee.emit('error', new Error('This will crash'));
});
</pre> <p>Errors generated in this way <em>cannot</em> be intercepted using <code>try / catch</code> as they are thrown <em>after</em> the calling code has already exited.</p> <p>Developers must refer to the documentation for each method to determine exactly how errors raised by those methods are propagated.</p> <h3 id="errors_error_first_callbacks">Error-first callbacks</h3>  <p>Most asynchronous methods exposed by the Node.js core API follow an idiomatic pattern referred to as an <em>error-first callback</em> (sometimes referred to as a <em>Node.js style callback</em>). With this pattern, a callback function is passed to the method as an argument. When the operation either completes or an error is raised, the callback function is called with the Error object (if any) passed as the first argument. If no error was raised, the first argument will be passed as <code>null</code>.</p> <pre data-language="js">const fs = require('fs');

function errorFirstCallback(err, data) {
  if (err) {
    console.error('There was an error', err);
    return;
  }
  console.log(data);
}

fs.readFile('/some/file/that/does-not-exist', errorFirstCallback);
fs.readFile('/some/file/that/does-exist', errorFirstCallback);
</pre> <p>The JavaScript <code>try / catch</code> mechanism <strong>cannot</strong> be used to intercept errors generated by asynchronous APIs. A common mistake for beginners is to try to use <code>throw</code> inside an error-first callback:</p> <pre data-language="js">// THIS WILL NOT WORK:
const fs = require('fs');

try {
  fs.readFile('/some/file/that/does-not-exist', (err, data) =&gt; {
    // mistaken assumption: throwing here...
    if (err) {
      throw err;
    }
  });
} catch (err) {
  // This will not catch the throw!
  console.error(err);
}
</pre> <p>This will not work because the callback function passed to <code>fs.readFile()</code> is called asynchronously. By the time the callback has been called, the surrounding code (including the <code>try { } catch (err) { }</code> block will have already exited. Throwing an error inside the callback <strong>can crash the Node.js process</strong> in most cases. If <a href="../domain/">domains</a> are enabled, or a handler has been registered with <code>process.on('uncaughtException')</code>, such errors can be intercepted.</p> <h2 id="errors_class_error">Class: Error</h2>  <p>A generic JavaScript <code>Error</code> object that does not denote any specific circumstance of why the error occurred. <code>Error</code> objects capture a "stack trace" detailing the point in the code at which the <code>Error</code> was instantiated, and may provide a text description of the error.</p> <p>For crypto only, <code>Error</code> objects will include the OpenSSL error stack in a separate property called <code>opensslErrorStack</code> if it is available when the error is thrown.</p> <p>All errors generated by Node.js, including all System and JavaScript errors, will either be instances of, or inherit from, the <code>Error</code> class.</p> <h3 id="errors_new_error_message">new Error(message)</h3> <div class="signature">
<ul> <li>
<code>message</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a>
</li> </ul> </div>
<p>Creates a new <code>Error</code> object and sets the <code>error.message</code> property to the provided text message. If an object is passed as <code>message</code>, the text message is generated by calling <code>message.toString()</code>. The <code>error.stack</code> property will represent the point in the code at which <code>new Error()</code> was called. Stack traces are dependent on <a href="https://github.com/v8/v8/wiki/Stack-Trace-API" target="_blank">V8's stack trace API</a>. Stack traces extend only to either (a) the beginning of <em>synchronous code execution</em>, or (b) the number of frames given by the property <code>Error.stackTraceLimit</code>, whichever is smaller.</p> <h3 id="errors_error_capturestacktrace_targetobject_constructoropt">Error.captureStackTrace(targetObject[, constructorOpt])</h3> <div class="signature">
<ul> <li>
<code>targetObject</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object" class="type" target="_blank">&lt;Object&gt;</a>
</li> <li>
<code>constructorOpt</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function" class="type" target="_blank">&lt;Function&gt;</a>
</li> </ul> </div>
<p>Creates a <code>.stack</code> property on <code>targetObject</code>, which when accessed returns a string representing the location in the code at which <code>Error.captureStackTrace()</code> was called.</p> <pre data-language="js">const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // similar to `new Error().stack`
</pre> <p>The first line of the trace will be prefixed with <code>${myObject.name}: ${myObject.message}</code>.</p> <p>The optional <code>constructorOpt</code> argument accepts a function. If given, all frames above <code>constructorOpt</code>, including <code>constructorOpt</code>, will be omitted from the generated stack trace.</p> <p>The <code>constructorOpt</code> argument is useful for hiding implementation details of error generation from an end user. For instance:</p> <pre data-language="js">function MyError() {
  Error.captureStackTrace(this, MyError);
}

// Without passing MyError to captureStackTrace, the MyError
// frame would show up in the .stack property. By passing
// the constructor, we omit that frame, and retain all frames below it.
new MyError().stack;
</pre> <h3 id="errors_error_stacktracelimit">Error.stackTraceLimit</h3> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type" target="_blank">&lt;number&gt;</a></li> </ul> </div>
<p>The <code>Error.stackTraceLimit</code> property specifies the number of stack frames collected by a stack trace (whether generated by <code>new Error().stack</code> or <code>Error.captureStackTrace(obj)</code>).</p> <p>The default value is <code>10</code> but may be set to any valid JavaScript number. Changes will affect any stack trace captured <em>after</em> the value has been changed.</p> <p>If set to a non-number value, or set to a negative number, stack traces will not capture any frames.</p> <h3 id="errors_error_code">error.code</h3> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>The <code>error.code</code> property is a string label that identifies the kind of error. See <a href="#nodejs-error-codes">Node.js Error Codes</a> for details about specific codes.</p> <h3 id="errors_error_message">error.message</h3> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>The <code>error.message</code> property is the string description of the error as set by calling <code>new Error(message)</code>. The <code>message</code> passed to the constructor will also appear in the first line of the stack trace of the <code>Error</code>, however changing this property after the <code>Error</code> object is created <em>may not</em> change the first line of the stack trace (for example, when <code>error.stack</code> is read before this property is changed).</p> <pre data-language="js">const err = new Error('The message');
console.error(err.message);
// Prints: The message
</pre> <h3 id="errors_error_stack">error.stack</h3> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>The <code>error.stack</code> property is a string describing the point in the code at which the <code>Error</code> was instantiated.</p> <p>For example:</p> <pre data-language="txt">Error: Things keep happening!
   at /home/gbusey/file.js:525:2
   at Frobnicator.refrobulate (/home/gbusey/business-logic.js:424:21)
   at Actor.&lt;anonymous&gt; (/home/gbusey/actors.js:400:8)
   at increaseSynergy (/home/gbusey/actors.js:701:6)
</pre> <p>The first line is formatted as <code>&lt;error class name&gt;: &lt;error message&gt;</code>, and is followed by a series of stack frames (each line beginning with "at "). Each frame describes a call site within the code that lead to the error being generated. V8 attempts to display a name for each function (by variable name, function name, or object method name), but occasionally it will not be able to find a suitable name. If V8 cannot determine a name for the function, only location information will be displayed for that frame. Otherwise, the determined function name will be displayed with location information appended in parentheses.</p> <p>Frames are only generated for JavaScript functions. If, for example, execution synchronously passes through a C++ addon function called <code>cheetahify</code> which itself calls a JavaScript function, the frame representing the <code>cheetahify</code> call will not be present in the stack traces:</p> <pre data-language="js">const cheetahify = require('./native-binding.node');

function makeFaster() {
  // cheetahify *synchronously* calls speedy.
  cheetahify(function speedy() {
    throw new Error('oh no!');
  });
}

makeFaster();
// will throw:
//   /home/gbusey/file.js:6
//       throw new Error('oh no!');
//           ^
//   Error: oh no!
//       at speedy (/home/gbusey/file.js:6:11)
//       at makeFaster (/home/gbusey/file.js:5:3)
//       at Object.&lt;anonymous&gt; (/home/gbusey/file.js:10:1)
//       at Module._compile (module.js:456:26)
//       at Object.Module._extensions..js (module.js:474:10)
//       at Module.load (module.js:356:32)
//       at Function.Module._load (module.js:312:12)
//       at Function.Module.runMain (module.js:497:10)
//       at startup (node.js:119:16)
//       at node.js:906:3
</pre> <p>The location information will be one of:</p> <ul> <li>
<code>native</code>, if the frame represents a call internal to V8 (as in <code>[].forEach</code>).</li> <li>
<code>plain-filename.js:line:column</code>, if the frame represents a call internal to Node.js.</li> <li>
<code>/absolute/path/to/file.js:line:column</code>, if the frame represents a call in a user program, or its dependencies.</li> </ul> <p>The string representing the stack trace is lazily generated when the <code>error.stack</code> property is <strong>accessed</strong>.</p> <p>The number of frames captured by the stack trace is bounded by the smaller of <code>Error.stackTraceLimit</code> or the number of available frames on the current event loop tick.</p> <p>System-level errors are generated as augmented <code>Error</code> instances, which are detailed <a href="#errors_system_errors">here</a>.</p> <h2 id="errors_class_assertionerror">Class: AssertionError</h2> <p>A subclass of <code>Error</code> that indicates the failure of an assertion. Such errors commonly indicate inequality of actual and expected value.</p> <p>For example:</p> <pre data-language="js">assert.strictEqual(1, 2);
// AssertionError [ERR_ASSERTION]: 1 === 2
</pre> <h2 id="errors_class_rangeerror">Class: RangeError</h2> <p>A subclass of <code>Error</code> that indicates that a provided argument was not within the set or range of acceptable values for a function; whether that is a numeric range, or outside the set of options for a given function parameter.</p> <p>For example:</p> <pre data-language="js">require('net').connect(-1);
// throws "RangeError: "port" option should be &gt;= 0 and &lt; 65536: -1"
</pre> <p>Node.js will generate and throw <code>RangeError</code> instances <em>immediately</em> as a form of argument validation.</p> <h2 id="errors_class_referenceerror">Class: ReferenceError</h2> <p>A subclass of <code>Error</code> that indicates that an attempt is being made to access a variable that is not defined. Such errors commonly indicate typos in code, or an otherwise broken program.</p> <p>While client code may generate and propagate these errors, in practice, only V8 will do so.</p> <pre data-language="js">doesNotExist;
// throws ReferenceError, doesNotExist is not a variable in this program.
</pre> <p>Unless an application is dynamically generating and running code, <code>ReferenceError</code> instances should always be considered a bug in the code or its dependencies.</p> <h2 id="errors_class_syntaxerror">Class: SyntaxError</h2> <p>A subclass of <code>Error</code> that indicates that a program is not valid JavaScript. These errors may only be generated and propagated as a result of code evaluation. Code evaluation may happen as a result of <code>eval</code>, <code>Function</code>, <code>require</code>, or <a href="../vm/">vm</a>. These errors are almost always indicative of a broken program.</p> <pre data-language="js">try {
  require('vm').runInThisContext('binary ! isNotOk');
} catch (err) {
  // err will be a SyntaxError
}
</pre> <p><code>SyntaxError</code> instances are unrecoverable in the context that created them – they may only be caught by other contexts.</p> <h2 id="errors_class_typeerror">Class: TypeError</h2> <p>A subclass of <code>Error</code> that indicates that a provided argument is not an allowable type. For example, passing a function to a parameter which expects a string would be considered a TypeError.</p> <pre data-language="js">require('url').parse(() =&gt; { });
// throws TypeError, since it expected a string
</pre> <p>Node.js will generate and throw <code>TypeError</code> instances <em>immediately</em> as a form of argument validation.</p> <h2 id="errors_exceptions_vs_errors">Exceptions vs. Errors</h2>  <p>A JavaScript exception is a value that is thrown as a result of an invalid operation or as the target of a <code>throw</code> statement. While it is not required that these values are instances of <code>Error</code> or classes which inherit from <code>Error</code>, all exceptions thrown by Node.js or the JavaScript runtime <em>will</em> be instances of Error.</p> <p>Some exceptions are <em>unrecoverable</em> at the JavaScript layer. Such exceptions will <em>always</em> cause the Node.js process to crash. Examples include <code>assert()</code> checks or <code>abort()</code> calls in the C++ layer.</p> <h2 id="errors_system_errors">System Errors</h2> <p>System errors are generated when exceptions occur within the program's runtime environment. Typically, these are operational errors that occur when an application violates an operating system constraint such as attempting to read a file that does not exist or when the user does not have sufficient permissions.</p> <p>System errors are typically generated at the syscall level: an exhaustive list of error codes and their meanings is available by running <code>man 2 intro</code> or <code>man 3 errno</code> on most Unices; or <a href="http://man7.org/linux/man-pages/man3/errno.3.html" target="_blank">online</a>.</p> <p>In Node.js, system errors are represented as augmented <code>Error</code> objects with added properties.</p> <h3 id="errors_class_system_error">Class: System Error</h3> <h4 id="errors_error_code_1">error.code</h4> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>The <code>error.code</code> property is a string representing the error code, which is typically <code>E</code> followed by a sequence of capital letters.</p> <h4 id="errors_error_errno">error.errno</h4> <div class="signature">
<ul> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a> | <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type" target="_blank">&lt;number&gt;</a>
</li> </ul> </div>
<p>The <code>error.errno</code> property is a number or a string. The number is a <strong>negative</strong> value which corresponds to the error code defined in <a href="http://docs.libuv.org/en/v1.x/errors.html" target="_blank"><code>libuv Error handling</code></a>. See uv-errno.h header file (<code>deps/uv/include/uv-errno.h</code> in the Node.js source tree) for details. In case of a string, it is the same as <code>error.code</code>.</p> <h4 id="errors_error_syscall">error.syscall</h4> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>The <code>error.syscall</code> property is a string describing the <a href="http://man7.org/linux/man-pages/man2/syscall.2.html" target="_blank">syscall</a> that failed.</p> <h4 id="errors_error_path">error.path</h4> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>When present (e.g. in <code>fs</code> or <code>child_process</code>), the <code>error.path</code> property is a string containing a relevant invalid pathname.</p> <h4 id="errors_error_address">error.address</h4> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>When present (e.g. in <code>net</code> or <code>dgram</code>), the <code>error.address</code> property is a string describing the address to which the connection failed.</p> <h4 id="errors_error_port">error.port</h4> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type" target="_blank">&lt;number&gt;</a></li> </ul> </div>
<p>When present (e.g. in <code>net</code> or <code>dgram</code>), the <code>error.port</code> property is a number representing the connection's port that is not available.</p> <h3 id="errors_common_system_errors">Common System Errors</h3> <p>This list is <strong>not exhaustive</strong>, but enumerates many of the common system errors encountered when writing a Node.js program. An exhaustive list may be found <a href="http://man7.org/linux/man-pages/man3/errno.3.html" target="_blank">here</a>.</p> <ul> <li>
<p><code>EACCES</code> (Permission denied): An attempt was made to access a file in a way forbidden by its file access permissions.</p> </li> <li>
<p><code>EADDRINUSE</code> (Address already in use): An attempt to bind a server (<a href="../net/"><code>net</code></a>, <a href="http" target="_blank"><code>http</code></a>, or <a href="https" target="_blank"><code>https</code></a>) to a local address failed due to another server on the local system already occupying that address.</p> </li> <li>
<p><code>ECONNREFUSED</code> (Connection refused): No connection could be made because the target machine actively refused it. This usually results from trying to connect to a service that is inactive on the foreign host.</p> </li> <li>
<p><code>ECONNRESET</code> (Connection reset by peer): A connection was forcibly closed by a peer. This normally results from a loss of the connection on the remote socket due to a timeout or reboot. Commonly encountered via the <a href="http" target="_blank"><code>http</code></a> and <a href="../net/"><code>net</code></a> modules.</p> </li> <li>
<p><code>EEXIST</code> (File exists): An existing file was the target of an operation that required that the target not exist.</p> </li> <li>
<p><code>EISDIR</code> (Is a directory): An operation expected a file, but the given pathname was a directory.</p> </li> <li>
<p><code>EMFILE</code> (Too many open files in system): Maximum number of <a href="https://en.wikipedia.org/wiki/File_descriptor" target="_blank">file descriptors</a> allowable on the system has been reached, and requests for another descriptor cannot be fulfilled until at least one has been closed. This is encountered when opening many files at once in parallel, especially on systems (in particular, macOS) where there is a low file descriptor limit for processes. To remedy a low limit, run <code>ulimit -n 2048</code> in the same shell that will run the Node.js process.</p> </li> <li>
<p><code>ENOENT</code> (No such file or directory): Commonly raised by <a href="../fs/"><code>fs</code></a> operations to indicate that a component of the specified pathname does not exist — no entity (file or directory) could be found by the given path.</p> </li> <li>
<p><code>ENOTDIR</code> (Not a directory): A component of the given pathname existed, but was not a directory as expected. Commonly raised by <a href="../fs/#fs_fs_readdir_path_options_callback"><code>fs.readdir</code></a>.</p> </li> <li>
<p><code>ENOTEMPTY</code> (Directory not empty): A directory with entries was the target of an operation that requires an empty directory — usually <a href="../fs/#fs_fs_unlink_path_callback"><code>fs.unlink</code></a>.</p> </li> <li>
<p><code>EPERM</code> (Operation not permitted): An attempt was made to perform an operation that requires elevated privileges.</p> </li> <li>
<p><code>EPIPE</code> (Broken pipe): A write on a pipe, socket, or FIFO for which there is no process to read the data. Commonly encountered at the <a href="../net/"><code>net</code></a> and <a href="http" target="_blank"><code>http</code></a> layers, indicative that the remote side of the stream being written to has been closed.</p> </li> <li>
<p><code>ETIMEDOUT</code> (Operation timed out): A connect or send request failed because the connected party did not properly respond after a period of time. Usually encountered by <a href="http" target="_blank"><code>http</code></a> or <a href="../net/"><code>net</code></a> — often a sign that a <code>socket.end()</code> was not properly called.</p> </li> </ul>  <h2 id="errors_node_js_error_codes">Node.js Error Codes</h2>  <h3 id="ERR_ARG_NOT_ITERABLE">ERR_ARG_NOT_ITERABLE</h3> <p>An iterable argument (i.e. a value that works with <code>for...of</code> loops) was required, but not provided to a Node.js API.</p>  <h3 id="ERR_ASYNC_CALLBACK">ERR_ASYNC_CALLBACK</h3> <p>An attempt was made to register something that is not a function as an <code>AsyncHooks</code> callback.</p>  <h3 id="ERR_ASYNC_TYPE">ERR_ASYNC_TYPE</h3> <p>The type of an asynchronous resource was invalid. Note that users are also able to define their own types if using the public embedder API.</p>  <h3 id="ERR_ENCODING_INVALID_ENCODED_DATA">ERR_ENCODING_INVALID_ENCODED_DATA</h3> <p>Data provided to <code>util.TextDecoder()</code> API was invalid according to the encoding provided.</p>  <h3 id="ERR_ENCODING_NOT_SUPPORTED">ERR_ENCODING_NOT_SUPPORTED</h3> <p>Encoding provided to <code>util.TextDecoder()</code> API was not one of the <a href="../util.md/#whatwg-supported-encodings">WHATWG Supported Encodings</a>.</p>  <h3 id="ERR_FALSY_VALUE_REJECTION">ERR_FALSY_VALUE_REJECTION</h3> <p>A <code>Promise</code> that was callbackified via <code>util.callbackify()</code> was rejected with a falsy value.</p>  <h3 id="ERR_HTTP_HEADERS_SENT">ERR_HTTP_HEADERS_SENT</h3> <p>An attempt was made to add more headers after the headers had already been sent.</p>  <h3 id="ERR_HTTP_INVALID_CHAR">ERR_HTTP_INVALID_CHAR</h3> <p>An invalid character was found in an HTTP response status message (reason phrase).</p>  <h3 id="ERR_HTTP_INVALID_STATUS_CODE">ERR_HTTP_INVALID_STATUS_CODE</h3> <p>Status code was outside the regular status code range (100-999).</p>  <h3 id="ERR_HTTP_TRAILER_INVALID">ERR_HTTP_TRAILER_INVALID</h3> <p>The <code>Trailer</code> header was set even though the transfer encoding does not support that.</p>  <h3 id="ERR_HTTP2_ALREADY_SHUTDOWN">ERR_HTTP2_ALREADY_SHUTDOWN</h3> <p>Occurs with multiple attempts to shutdown an HTTP/2 session.</p>  <h3 id="ERR_HTTP2_ALTSVC_INVALID_ORIGIN">ERR_HTTP2_ALTSVC_INVALID_ORIGIN</h3> <p>HTTP/2 ALTSVC frames require a valid origin.</p>  <h3 id="ERR_HTTP2_ALTSVC_LENGTH">ERR_HTTP2_ALTSVC_LENGTH</h3> <p>HTTP/2 ALTSVC frames are limited to a maximum of 16,382 payload bytes.</p>  <h3 id="ERR_HTTP2_CONNECT_AUTHORITY">ERR_HTTP2_CONNECT_AUTHORITY</h3> <p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:authority</code> pseudo-header is required.</p>  <h3 id="ERR_HTTP2_CONNECT_PATH">ERR_HTTP2_CONNECT_PATH</h3> <p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:path</code> pseudo-header is forbidden.</p>  <h3 id="ERR_HTTP2_CONNECT_SCHEME">ERR_HTTP2_CONNECT_SCHEME</h3> <p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:scheme</code> pseudo-header is forbidden.</p>  <h3 id="ERR_HTTP2_FRAME_ERROR">ERR_HTTP2_FRAME_ERROR</h3> <p>A failure occurred sending an individual frame on the HTTP/2 session.</p>  <h3 id="ERR_HTTP2_GOAWAY_SESSION">ERR_HTTP2_GOAWAY_SESSION</h3> <p>New HTTP/2 Streams may not be opened after the <code>Http2Session</code> has received a <code>GOAWAY</code> frame from the connected peer.</p>  <h3 id="ERR_HTTP2_HEADER_REQUIRED">ERR_HTTP2_HEADER_REQUIRED</h3> <p>A required header was missing in an HTTP/2 message.</p>  <h3 id="ERR_HTTP2_HEADER_SINGLE_VALUE">ERR_HTTP2_HEADER_SINGLE_VALUE</h3> <p>Multiple values were provided for an HTTP/2 header field that was required to have only a single value.</p>  <h3 id="ERR_HTTP2_HEADERS_AFTER_RESPOND">ERR_HTTP2_HEADERS_AFTER_RESPOND</h3> <p>An additional headers was specified after an HTTP/2 response was initiated.</p>  <h3 id="ERR_HTTP2_HEADERS_OBJECT">ERR_HTTP2_HEADERS_OBJECT</h3> <p>An HTTP/2 Headers Object was expected.</p>  <h3 id="ERR_HTTP2_HEADERS_SENT">ERR_HTTP2_HEADERS_SENT</h3> <p>An attempt was made to send multiple response headers.</p>  <h3 id="ERR_HTTP2_INFO_HEADERS_AFTER_RESPOND">ERR_HTTP2_INFO_HEADERS_AFTER_RESPOND</h3> <p>HTTP/2 Informational headers must only be sent <em>prior</em> to calling the <code>Http2Stream.prototype.respond()</code> method.</p>  <h3 id="ERR_HTTP2_INFO_STATUS_NOT_ALLOWED">ERR_HTTP2_INFO_STATUS_NOT_ALLOWED</h3> <p>Informational HTTP status codes (<code>1xx</code>) may not be set as the response status code on HTTP/2 responses.</p>  <h3 id="ERR_HTTP2_INVALID_CONNECTION_HEADERS">ERR_HTTP2_INVALID_CONNECTION_HEADERS</h3> <p>HTTP/1 connection specific headers are forbidden to be used in HTTP/2 requests and responses.</p>  <h3 id="ERR_HTTP2_INVALID_HEADER_VALUE">ERR_HTTP2_INVALID_HEADER_VALUE</h3> <p>An invalid HTTP/2 header value was specified.</p>  <h3 id="ERR_HTTP2_INVALID_INFO_STATUS">ERR_HTTP2_INVALID_INFO_STATUS</h3> <p>An invalid HTTP informational status code has been specified. Informational status codes must be an integer between <code>100</code> and <code>199</code> (inclusive).</p>  <h3 id="ERR_HTTP2_INVALID_ORIGIN">ERR_HTTP2_INVALID_ORIGIN</h3> <p>HTTP/2 <code>ORIGIN</code> frames require a valid origin.</p>  <h3 id="ERR_HTTP2_INVALID_PACKED_SETTINGS_LENGTH">ERR_HTTP2_INVALID_PACKED_SETTINGS_LENGTH</h3> <p>Input <code>Buffer</code> and <code>Uint8Array</code> instances passed to the <code>http2.getUnpackedSettings()</code> API must have a length that is a multiple of six.</p>  <h3 id="ERR_HTTP2_INVALID_PSEUDOHEADER">ERR_HTTP2_INVALID_PSEUDOHEADER</h3> <p>Only valid HTTP/2 pseudoheaders (<code>:status</code>, <code>:path</code>, <code>:authority</code>, <code>:scheme</code>, and <code>:method</code>) may be used.</p>  <h3 id="ERR_HTTP2_INVALID_SESSION">ERR_HTTP2_INVALID_SESSION</h3> <p>An action was performed on an <code>Http2Session</code> object that had already been destroyed.</p>  <h3 id="ERR_HTTP2_INVALID_SETTING_VALUE">ERR_HTTP2_INVALID_SETTING_VALUE</h3> <p>An invalid value has been specified for an HTTP/2 setting.</p>  <h3 id="ERR_HTTP2_INVALID_STREAM">ERR_HTTP2_INVALID_STREAM</h3> <p>An operation was performed on a stream that had already been destroyed.</p>  <h3 id="ERR_HTTP2_MAX_PENDING_SETTINGS_ACK">ERR_HTTP2_MAX_PENDING_SETTINGS_ACK</h3> <p>Whenever an HTTP/2 <code>SETTINGS</code> frame is sent to a connected peer, the peer is required to send an acknowledgment that it has received and applied the new <code>SETTINGS</code>. By default, a maximum number of unacknowledged <code>SETTINGS</code> frames may be sent at any given time. This error code is used when that limit has been reached.</p>  <h3 id="ERR_HTTP2_NESTED_PUSH">ERR_HTTP2_NESTED_PUSH</h3> <p>An attempt was made to initiate a new push stream from within a push stream. Nested push streams are not permitted.</p>  <h3 id="ERR_HTTP2_NO_SOCKET_MANIPULATION">ERR_HTTP2_NO_SOCKET_MANIPULATION</h3> <p>An attempt was made to directly manipulate (read, write, pause, resume, etc.) a socket attached to an <code>Http2Session</code>.</p>  <h3 id="ERR_HTTP2_ORIGIN_LENGTH">ERR_HTTP2_ORIGIN_LENGTH</h3> <p>HTTP/2 <code>ORIGIN</code> frames are limited to a length of 16382 bytes.</p>  <h3 id="ERR_HTTP2_OUT_OF_STREAMS">ERR_HTTP2_OUT_OF_STREAMS</h3> <p>The number of streams created on a single HTTP/2 session reached the maximum limit.</p>  <h3 id="ERR_HTTP2_PAYLOAD_FORBIDDEN">ERR_HTTP2_PAYLOAD_FORBIDDEN</h3> <p>A message payload was specified for an HTTP response code for which a payload is forbidden.</p>  <h3 id="ERR_HTTP2_PING_CANCEL">ERR_HTTP2_PING_CANCEL</h3> <p>An HTTP/2 ping was canceled.</p>  <h3 id="ERR_HTTP2_PING_LENGTH">ERR_HTTP2_PING_LENGTH</h3> <p>HTTP/2 ping payloads must be exactly 8 bytes in length.</p>  <h3 id="ERR_HTTP2_PSEUDOHEADER_NOT_ALLOWED">ERR_HTTP2_PSEUDOHEADER_NOT_ALLOWED</h3> <p>An HTTP/2 pseudo-header has been used inappropriately. Pseudo-headers are header key names that begin with the <code>:</code> prefix.</p>  <h3 id="ERR_HTTP2_PUSH_DISABLED">ERR_HTTP2_PUSH_DISABLED</h3> <p>An attempt was made to create a push stream, which had been disabled by the client.</p>  <h3 id="ERR_HTTP2_SEND_FILE">ERR_HTTP2_SEND_FILE</h3> <p>An attempt was made to use the <code>Http2Stream.prototype.responseWithFile()</code> API to send something other than a regular file.</p>  <h3 id="ERR_HTTP2_SESSION_ERROR">ERR_HTTP2_SESSION_ERROR</h3> <p>The <code>Http2Session</code> closed with a non-zero error code.</p>  <h3 id="ERR_HTTP2_SETTINGS_CANCEL">ERR_HTTP2_SETTINGS_CANCEL</h3> <p>The <code>Http2Session</code> settings canceled.</p>  <h3 id="ERR_HTTP2_SOCKET_BOUND">ERR_HTTP2_SOCKET_BOUND</h3> <p>An attempt was made to connect a <code>Http2Session</code> object to a <code>net.Socket</code> or <code>tls.TLSSocket</code> that had already been bound to another <code>Http2Session</code> object.</p>  <h3 id="ERR_HTTP2_SOCKET_UNBOUND">ERR_HTTP2_SOCKET_UNBOUND</h3> <p>An attempt was made to use the <code>socket</code> property of an <code>Http2Session</code> that has already been closed.</p>  <h3 id="ERR_HTTP2_STATUS_101">ERR_HTTP2_STATUS_101</h3> <p>Use of the <code>101</code> Informational status code is forbidden in HTTP/2.</p>  <h3 id="ERR_HTTP2_STATUS_INVALID">ERR_HTTP2_STATUS_INVALID</h3> <p>An invalid HTTP status code has been specified. Status codes must be an integer between <code>100</code> and <code>599</code> (inclusive).</p>  <h3 id="ERR_HTTP2_STREAM_CANCEL">ERR_HTTP2_STREAM_CANCEL</h3> <p>An <code>Http2Stream</code> was destroyed before any data was transmitted to the connected peer.</p>  <h3 id="ERR_HTTP2_STREAM_ERROR">ERR_HTTP2_STREAM_ERROR</h3> <p>A non-zero error code was been specified in an <code>RST_STREAM</code> frame.</p>  <h3 id="ERR_HTTP2_STREAM_SELF_DEPENDENCY">ERR_HTTP2_STREAM_SELF_DEPENDENCY</h3> <p>When setting the priority for an HTTP/2 stream, the stream may be marked as a dependency for a parent stream. This error code is used when an attempt is made to mark a stream and dependent of itself.</p>  <h3 id="ERR_HTTP2_TRAILERS_ALREADY_SENT">ERR_HTTP2_TRAILERS_ALREADY_SENT</h3> <p>Trailing headers have already been sent on the <code>Http2Stream</code>.</p>  <h3 id="ERR_HTTP2_TRAILERS_NOT_READY">ERR_HTTP2_TRAILERS_NOT_READY</h3> <p>The <code>http2stream.sendTrailers()</code> method cannot be called until after the <code>'wantTrailers'</code> event is emitted on an <code>Http2Stream</code> object. The <code>'wantTrailers'</code> event will only be emitted if the <code>waitForTrailers</code> option is set for the <code>Http2Stream</code>.</p>  <h3 id="ERR_HTTP2_UNSUPPORTED_PROTOCOL">ERR_HTTP2_UNSUPPORTED_PROTOCOL</h3> <p><code>http2.connect()</code> was passed a URL that uses any protocol other than <code>http:</code> or <code>https:</code>.</p>  <h3 id="ERR_INDEX_OUT_OF_RANGE">ERR_INDEX_OUT_OF_RANGE</h3> <p>A given index was out of the accepted range (e.g. negative offsets).</p>  <h3 id="ERR_INVALID_ARG_TYPE">ERR_INVALID_ARG_TYPE</h3> <p>An argument of the wrong type was passed to a Node.js API.</p>  <h3 id="ERR_INVALID_ASYNC_ID">ERR_INVALID_ASYNC_ID</h3> <p>An invalid <code>asyncId</code> or <code>triggerAsyncId</code> was passed using <code>AsyncHooks</code>. An id less than -1 should never happen.</p>  <h3 id="ERR_INVALID_CALLBACK">ERR_INVALID_CALLBACK</h3> <p>A callback function was required but was not been provided to a Node.js API.</p>  <h3 id="ERR_INVALID_FILE_URL_HOST">ERR_INVALID_FILE_URL_HOST</h3> <p>A Node.js API that consumes <code>file:</code> URLs (such as certain functions in the <a href="../fs/"><code>fs</code></a> module) encountered a file URL with an incompatible host. This situation can only occur on Unix-like systems where only <code>localhost</code> or an empty host is supported.</p>  <h3 id="ERR_INVALID_FILE_URL_PATH">ERR_INVALID_FILE_URL_PATH</h3> <p>A Node.js API that consumes <code>file:</code> URLs (such as certain functions in the <a href="../fs/"><code>fs</code></a> module) encountered a file URL with an incompatible path. The exact semantics for determining whether a path can be used is platform-dependent.</p>  <h3 id="ERR_INVALID_HANDLE_TYPE">ERR_INVALID_HANDLE_TYPE</h3> <p>An attempt was made to send an unsupported "handle" over an IPC communication channel to a child process. See <a href="../child_process/#child_process_subprocess_send_message_sendhandle_options_callback"><code>subprocess.send()</code></a> and <a href="../process/#process_process_send_message_sendhandle_options_callback"><code>process.send()</code></a> for more information.</p>  <h3 id="ERR_INVALID_OPT_VALUE">ERR_INVALID_OPT_VALUE</h3> <p>An invalid or unexpected value was passed in an options object.</p>  <h3 id="ERR_INVALID_PERFORMANCE_MARK">ERR_INVALID_PERFORMANCE_MARK</h3> <p>While using the Performance Timing API (<code>perf_hooks</code>), a performance mark is invalid.</p>  <h3 id="ERR_INVALID_PROTOCOL">ERR_INVALID_PROTOCOL</h3> <p>An invalid <code>options.protocol</code> was passed.</p>  <h3 id="ERR_INVALID_SYNC_FORK_INPUT">ERR_INVALID_SYNC_FORK_INPUT</h3> <p>A <code>Buffer</code>, <code>Uint8Array</code> or <code>string</code> was provided as stdio input to a synchronous fork. See the documentation for the <a href="../child_process/"><code>child_process</code></a> module for more information.</p>  <h3 id="ERR_INVALID_THIS">ERR_INVALID_THIS</h3> <p>A Node.js API function was called with an incompatible <code>this</code> value.</p> <p>Example:</p> <pre data-language="js">const { URLSearchParams } = require('url');
const urlSearchParams = new URLSearchParams('foo=bar&amp;baz=new');

const buf = Buffer.alloc(1);
urlSearchParams.has.call(buf, 'foo');
// Throws a TypeError with code 'ERR_INVALID_THIS'
</pre>  <h3 id="ERR_INVALID_TUPLE">ERR_INVALID_TUPLE</h3> <p>An element in the <code>iterable</code> provided to the <a href="../url/#url_the_whatwg_url_api">WHATWG</a> <a href="../url/#url_constructor_new_urlsearchparams_iterable"><code>URLSearchParams</code> constructor</a> did not represent a <code>[name, value]</code> tuple – that is, if an element is not iterable, or does not consist of exactly two elements.</p>  <h3 id="ERR_INVALID_URL">ERR_INVALID_URL</h3> <p>An invalid URL was passed to the <a href="../url/#url_the_whatwg_url_api">WHATWG</a> <a href="../url/#url_constructor_new_url_input_base"><code>URL</code> constructor</a> to be parsed. The thrown error object typically has an additional property <code>'input'</code> that contains the URL that failed to parse.</p>  <h3 id="ERR_INVALID_URL_SCHEME">ERR_INVALID_URL_SCHEME</h3> <p>An attempt was made to use a URL of an incompatible scheme (protocol) for a specific purpose. It is only used in the <a href="../url/#url_the_whatwg_url_api">WHATWG URL API</a> support in the <a href="../fs/"><code>fs</code></a> module (which only accepts URLs with <code>'file'</code> scheme), but may be used in other Node.js APIs as well in the future.</p>  <h3 id="ERR_IPC_CHANNEL_CLOSED">ERR_IPC_CHANNEL_CLOSED</h3> <p>An attempt was made to use an IPC communication channel that was already closed.</p>  <h3 id="ERR_IPC_DISCONNECTED">ERR_IPC_DISCONNECTED</h3> <p>An attempt was made to disconnect an IPC communication channel that was already disconnected. See the documentation for the <a href="../child_process/"><code>child_process</code></a> module for more information.</p>  <h3 id="ERR_IPC_ONE_PIPE">ERR_IPC_ONE_PIPE</h3> <p>An attempt was made to create a child Node.js process using more than one IPC communication channel. See the documentation for the <a href="../child_process/"><code>child_process</code></a> module for more information.</p>  <h3 id="ERR_IPC_SYNC_FORK">ERR_IPC_SYNC_FORK</h3> <p>An attempt was made to open an IPC communication channel with a synchronously forked Node.js process. See the documentation for the <a href="../child_process/"><code>child_process</code></a> module for more information.</p>  <h3 id="ERR_MISSING_ARGS">ERR_MISSING_ARGS</h3> <p>A required argument of a Node.js API was not passed. This is only used for strict compliance with the API specification (which in some cases may accept <code>func(undefined)</code> but not <code>func()</code>). In most native Node.js APIs, <code>func(undefined)</code> and <code>func()</code> are treated identically, and the <a href="#ERR_INVALID_ARG_TYPE"><code>ERR_INVALID_ARG_TYPE</code></a> error code may be used instead.</p>  <h3 id="ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK">ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK</h3> <div class="api_stability api_stability_1">
<a href="https://nodejs.org/dist/latest-v8.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 1</a> - Experimental</div>
<p>Used when an [ES6 module][] loader hook specifies <code>format: 'dynamic</code> but does not provide a <code>dynamicInstantiate</code> hook.</p>  <h3 id="ERR_MISSING_MODULE">ERR_MISSING_MODULE</h3> <div class="api_stability api_stability_1">
<a href="https://nodejs.org/dist/latest-v8.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 1</a> - Experimental</div>
<p>Used when an [ES6 module][] cannot be resolved.</p>  <h3 id="ERR_MODULE_RESOLUTION_LEGACY">ERR_MODULE_RESOLUTION_LEGACY</h3> <div class="api_stability api_stability_1">
<a href="https://nodejs.org/dist/latest-v8.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 1</a> - Experimental</div>
<p>Used when a failure occurred resolving imports in an [ES6 module][].</p>  <h3 id="ERR_MULTIPLE_CALLBACK">ERR_MULTIPLE_CALLBACK</h3> <p>A callback was called more than once.</p> <p><em>Note</em>: A callback is almost always meant to only be called once as the query can either be fulfilled or rejected but not both at the same time. The latter would be possible by calling a callback more than once.</p>  <h3 id="ERR_NAPI_CONS_FUNCTION">ERR_NAPI_CONS_FUNCTION</h3> <p>While using <code>N-API</code>, a constructor passed was not a function.</p>  <h3 id="ERR_NAPI_CONS_PROTOTYPE_OBJECT">ERR_NAPI_CONS_PROTOTYPE_OBJECT</h3> <p>While using <code>N-API</code>, <code>Constructor.prototype</code> was not an object.</p>  <h3 id="ERR_NAPI_INVALID_DATAVIEW_ARGS">ERR_NAPI_INVALID_DATAVIEW_ARGS</h3> <p>While calling <code>napi_create_dataview()</code>, a given <code>offset</code> was outside the bounds of the dataview or <code>offset + length</code> was larger than a length of given <code>buffer</code>.</p>  <h3 id="ERR_NAPI_INVALID_TYPEDARRAY_ALIGNMENT">ERR_NAPI_INVALID_TYPEDARRAY_ALIGNMENT</h3> <p>While calling <code>napi_create_typedarray()</code>, the provided <code>offset</code> was not a multiple of the element size.</p>  <h3 id="ERR_NAPI_INVALID_TYPEDARRAY_LENGTH">ERR_NAPI_INVALID_TYPEDARRAY_LENGTH</h3> <p>While calling <code>napi_create_typedarray()</code>, <code>(length * size_of_element) +
byte_offset</code> was larger than the length of given <code>buffer</code>.</p>  <h3 id="ERR_NAPI_TSFN_CALL_JS">ERR_NAPI_TSFN_CALL_JS</h3> <p>An error occurred while invoking the JavaScript portion of the thread-safe function.</p>  <h3 id="ERR_NAPI_TSFN_GET_UNDEFINED">ERR_NAPI_TSFN_GET_UNDEFINED</h3> <p>An error occurred while attempting to retrieve the JavaScript <code>undefined</code> value.</p>  <h3 id="ERR_NAPI_TSFN_START_IDLE_LOOP">ERR_NAPI_TSFN_START_IDLE_LOOP</h3> <p>On the main thread, values are removed from the queue associated with the thread-safe function in an idle loop. This error indicates that an error has occurred when attemping to start the loop.</p>  <h3 id="ERR_NAPI_TSFN_STOP_IDLE_LOOP">ERR_NAPI_TSFN_STOP_IDLE_LOOP</h3> <p>Once no more items are left in the queue, the idle loop must be suspended. This error indicates that the idle loop has failed to stop.</p>  <h3 id="ERR_NO_ICU">ERR_NO_ICU</h3> <p>An attempt was made to use features that require <a href="../intl/#intl_internationalization_support">ICU</a>, but Node.js was not compiled with ICU support.</p>  <h3 id="ERR_SOCKET_ALREADY_BOUND">ERR_SOCKET_ALREADY_BOUND</h3> <p>An attempt was made to bind a socket that has already been bound.</p>  <h3 id="ERR_SOCKET_BAD_PORT">ERR_SOCKET_BAD_PORT</h3> <p>An API function expecting a port &gt; 0 and &lt; 65536 received an invalid value.</p>  <h3 id="ERR_SOCKET_BAD_TYPE">ERR_SOCKET_BAD_TYPE</h3> <p>An API function expecting a socket type (<code>udp4</code> or <code>udp6</code>) received an invalid value.</p>  <h3 id="ERR_SOCKET_CANNOT_SEND">ERR_SOCKET_CANNOT_SEND</h3> <p>Data could be sent on a socket.</p>  <h3 id="ERR_SOCKET_CLOSED">ERR_SOCKET_CLOSED</h3> <p>An attempt was made to operate on an already closed socket.</p>  <h3 id="ERR_SOCKET_DGRAM_NOT_RUNNING">ERR_SOCKET_DGRAM_NOT_RUNNING</h3> <p>A call was made and the UDP subsystem was not running.</p>  <h3 id="ERR_STDERR_CLOSE">ERR_STDERR_CLOSE</h3> <div class="api_metadata"> <details class="changelog"><summary>History</summary> <table> <tr>
<th>Version</th>
<th>Changes</th>
</tr> <tr>
<td>v8.16.0</td> <td>
<p>Rather than emitting an error, <code>process.stderr.end()</code> now only closes the stream side but not the underlying resource, making this error obsolete.</p> </td>
</tr> </table> </details> </div>
<p>An attempt was made to close the <code>process.stderr</code> stream. By design, Node.js does not allow <code>stdout</code> or <code>stderr</code> streams to be closed by user code.</p>  <h3 id="ERR_STDOUT_CLOSE">ERR_STDOUT_CLOSE</h3> <div class="api_metadata"> <details class="changelog"><summary>History</summary> <table> <tr>
<th>Version</th>
<th>Changes</th>
</tr> <tr>
<td>v8.16.0</td> <td>
<p>Rather than emitting an error, <code>process.stderr.end()</code> now only closes the stream side but not the underlying resource, making this error obsolete.</p> </td>
</tr> </table> </details> </div>
<p>An attempt was made to close the <code>process.stdout</code> stream. By design, Node.js does not allow <code>stdout</code> or <code>stderr</code> streams to be closed by user code.</p>  <h3 id="ERR_TLS_CERT_ALTNAME_INVALID">ERR_TLS_CERT_ALTNAME_INVALID</h3> <p>While using TLS, the hostname/IP of the peer did not match any of the subjectAltNames in its certificate.</p>  <h3 id="ERR_TLS_DH_PARAM_SIZE">ERR_TLS_DH_PARAM_SIZE</h3> <p>While using TLS, the parameter offered for the Diffie-Hellman (<code>DH</code>) key-agreement protocol is too small. By default, the key length must be greater than or equal to 1024 bits to avoid vulnerabilities, even though it is strongly recommended to use 2048 bits or larger for stronger security.</p>  <h3 id="ERR_TLS_HANDSHAKE_TIMEOUT">ERR_TLS_HANDSHAKE_TIMEOUT</h3> <p>A TLS/SSL handshake timed out. In this case, the server must also abort the connection.</p>  <h3 id="ERR_TLS_RENEGOTIATION_FAILED">ERR_TLS_RENEGOTIATION_FAILED</h3> <p>A TLS renegotiation request has failed in a non-specific way.</p>  <h3 id="ERR_TLS_REQUIRED_SERVER_NAME">ERR_TLS_REQUIRED_SERVER_NAME</h3> <p>While using TLS, the <code>server.addContext()</code> method was called without providing a hostname in the first parameter.</p>  <h3 id="ERR_TLS_SESSION_ATTACK">ERR_TLS_SESSION_ATTACK</h3> <p>An excessive amount of TLS renegotiations is detected, which is a potential vector for denial-of-service attacks.</p>  <h3 id="ERR_TRANSFORM_ALREADY_TRANSFORMING">ERR_TRANSFORM_ALREADY_TRANSFORMING</h3> <p>A Transform stream finished while it was still transforming.</p>  <h3 id="ERR_TRANSFORM_WITH_LENGTH_0">ERR_TRANSFORM_WITH_LENGTH_0</h3> <p>A Transform stream finished with data still in the write buffer.</p>  <h3 id="ERR_UNKNOWN_SIGNAL">ERR_UNKNOWN_SIGNAL</h3> <p>An invalid or unknown process signal was passed to an API expecting a valid signal (such as <a href="../child_process/#child_process_subprocess_kill_signal"><code>subprocess.kill()</code></a>).</p>  <h3 id="ERR_UNKNOWN_STDIN_TYPE">ERR_UNKNOWN_STDIN_TYPE</h3> <p>An attempt was made to launch a Node.js process with an unknown <code>stdin</code> file type. This error is usually an indication of a bug within Node.js itself, although it is possible for user code to trigger it.</p>  <h3 id="ERR_UNKNOWN_STREAM_TYPE">ERR_UNKNOWN_STREAM_TYPE</h3> <p>An attempt was made to launch a Node.js process with an unknown <code>stdout</code> or <code>stderr</code> file type. This error is usually an indication of a bug within Node.js itself, although it is possible for user code to trigger it.</p>  <h3 id="ERR_V8BREAKITERATOR">ERR_V8BREAKITERATOR</h3> <p>The V8 BreakIterator API was used but the full ICU data set is not installed.</p>  <h3 id="ERR_VALID_PERFORMANCE_ENTRY_TYPE">ERR_VALID_PERFORMANCE_ENTRY_TYPE</h3> <p>While using the Performance Timing API (<code>perf_hooks</code>), no valid performance entry types were found.</p>  <h3 id="ERR_VALUE_OUT_OF_RANGE">ERR_VALUE_OUT_OF_RANGE</h3> <p>A given value is out of the accepted range.</p>
<div class="_attribution">
  <p class="_attribution-p">
    © Joyent, Inc. and other Node contributors<br>Licensed under the MIT License.<br>Node.js is a trademark of Joyent, Inc. and is used with its permission.<br>We are not endorsed by or affiliated with Joyent.<br>
    <a href="https://nodejs.org/dist/latest-v8.x/docs/api/errors.html" class="_attribution-link" target="_blank">https://nodejs.org/dist/latest-v8.x/docs/api/errors.html</a>
  </p>
</div>

				
			</div>
			<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
</amp-auto-ads>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
