
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Errors - Node.js - W3cubDocs</title>
  
  <meta name="description" content=" Applications running in Node.js will generally experience four categories of errors&#58; ">
  <meta name="keywords" content="errors, -, node, js">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="http://docs.w3cub.com/node/errors/">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" integrity="sha256-6/DH7X+2hvUPElJfGsvzm+tgIpmM9zjbYxnpsr6gR1A=" crossorigin="anonymous" href="/assets/application-ebf0c7ed7fb686f50f12525f1acbf39beb6022998cf738db6319e9b2bea04750.css">
  <script type="text/javascript" src="/assets/application-db285287b40ed28fac520fcfd75d7d874692b647b5b5e05968c741dda5de4148.js" integrity="sha256-2yhSh7QO0o+sUg/P1119h0aStke1teBZaMdB3aXeQUg=" crossorigin="anonymous"></script>
  <script src="/json/node.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-2572770204602497",
            enable_page_level_ads: true
        });
  </script>
  <script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body>
	<div class="_app">
	<header class="_header">
  
  <form class="_search">
    <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
    <a class="_search-clear"></a>
    <div class="_search-tag"></div>
  </form>
  
  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/node/" class="_nav-link" title="" style="margin-left:0;">Node.js</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		<div class="_list">
			
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="link"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _node">
				
				
<h1 id="errors_errors">Errors</h1> <p>Applications running in Node.js will generally experience four categories of errors:</p> <ul> <li>Standard JavaScript errors such as <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError" class="type" target="_blank">&lt;EvalError&gt;</a>, <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError" class="type" target="_blank">&lt;SyntaxError&gt;</a>, <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError" class="type" target="_blank">&lt;RangeError&gt;</a>, <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError" class="type" target="_blank">&lt;ReferenceError&gt;</a>, <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError" class="type" target="_blank">&lt;TypeError&gt;</a>, and <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError" class="type" target="_blank">&lt;URIError&gt;</a>.</li> <li>System errors triggered by underlying operating system constraints such as attempting to open a file that does not exist or attempting to send data over a closed socket.</li> <li>User-specified errors triggered by application code.</li> <li>
<code>AssertionError</code>s are a special class of error that can be triggered when Node.js detects an exceptional logic violation that should never occur. These are raised typically by the <code>assert</code> module.</li> </ul> <p>All JavaScript and System errors raised by Node.js inherit from, or are instances of, the standard JavaScript <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error" class="type" target="_blank">&lt;Error&gt;</a> class and are guaranteed to provide <em>at least</em> the properties available on that class.</p> <h2 id="errors_error_propagation_and_interception">Error Propagation and Interception</h2> <p>Node.js supports several mechanisms for propagating and handling errors that occur while an application is running. How these errors are reported and handled depends entirely on the type of <code>Error</code> and the style of the API that is called.</p> <p>All JavaScript errors are handled as exceptions that <em>immediately</em> generate and throw an error using the standard JavaScript <code>throw</code> mechanism. These are handled using the <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch" target="_blank"><code>try…catch</code> construct</a> provided by the JavaScript language.</p> <pre data-language="js">// Throws with a ReferenceError because z is not defined.
try {
  const m = 1;
  const n = m + z;
} catch (err) {
  // Handle the error here.
}
</pre> <p>Any use of the JavaScript <code>throw</code> mechanism will raise an exception that <em>must</em> be handled using <code>try…catch</code> or the Node.js process will exit immediately.</p> <p>With few exceptions, <em>Synchronous</em> APIs (any blocking method that does not accept a <code>callback</code> function, such as <a href="../fs/#fs_fs_readfilesync_path_options"><code>fs.readFileSync</code></a>), will use <code>throw</code> to report errors.</p> <p>Errors that occur within <em>Asynchronous APIs</em> may be reported in multiple ways:</p> <ul> <li>Most asynchronous methods that accept a <code>callback</code> function will accept an <code>Error</code> object passed as the first argument to that function. If that first argument is not <code>null</code> and is an instance of <code>Error</code>, then an error occurred that should be handled.</li> </ul>  <pre data-language="js">const fs = require('fs');
fs.readFile('a file that does not exist', (err, data) =&gt; {
  if (err) {
    console.error('There was an error reading the file!', err);
    return;
  }
  // Otherwise handle the data
});
</pre> <ul> <li> <p>When an asynchronous method is called on an object that is an <a href="../events/#events_class_eventemitter"><code>EventEmitter</code></a>, errors can be routed to that object's <code>'error'</code> event.</p> <pre data-language="js">const net = require('net');
const connection = net.connect('localhost');

// Adding an 'error' event handler to a stream:
connection.on('error', (err) =&gt; {
  // If the connection is reset by the server, or if it can't
  // connect at all, or on any sort of error encountered by
  // the connection, the error will be sent here.
  console.error(err);
});

connection.pipe(process.stdout);
</pre> </li> <li> <p>A handful of typically asynchronous methods in the Node.js API may still use the <code>throw</code> mechanism to raise exceptions that must be handled using <code>try…catch</code>. There is no comprehensive list of such methods; please refer to the documentation of each method to determine the appropriate error handling mechanism required.</p> </li> </ul> <p>The use of the <code>'error'</code> event mechanism is most common for <a href="../stream/">stream-based</a> and <a href="../events/#events_class_eventemitter">event emitter-based</a> APIs, which themselves represent a series of asynchronous operations over time (as opposed to a single operation that may pass or fail).</p> <p>For <em>all</em> <a href="../events/#events_class_eventemitter"><code>EventEmitter</code></a> objects, if an <code>'error'</code> event handler is not provided, the error will be thrown, causing the Node.js process to report an uncaught exception and crash unless either: The <a href="../domain/"><code>domain</code></a> module is used appropriately or a handler has been registered for the <a href="../process/#process_event_uncaughtexception"><code>'uncaughtException'</code></a> event.</p> <pre data-language="js">const EventEmitter = require('events');
const ee = new EventEmitter();

setImmediate(() =&gt; {
  // This will crash the process because no 'error' event
  // handler has been added.
  ee.emit('error', new Error('This will crash'));
});
</pre> <p>Errors generated in this way <em>cannot</em> be intercepted using <code>try…catch</code> as they are thrown <em>after</em> the calling code has already exited.</p> <p>Developers must refer to the documentation for each method to determine exactly how errors raised by those methods are propagated.</p> <h3 id="errors_error_first_callbacks">Error-first callbacks</h3> <p>Most asynchronous methods exposed by the Node.js core API follow an idiomatic pattern referred to as an <em>error-first callback</em>. With this pattern, a callback function is passed to the method as an argument. When the operation either completes or an error is raised, the callback function is called with the <code>Error</code> object (if any) passed as the first argument. If no error was raised, the first argument will be passed as <code>null</code>.</p> <pre data-language="js">const fs = require('fs');

function errorFirstCallback(err, data) {
  if (err) {
    console.error('There was an error', err);
    return;
  }
  console.log(data);
}

fs.readFile('/some/file/that/does-not-exist', errorFirstCallback);
fs.readFile('/some/file/that/does-exist', errorFirstCallback);
</pre> <p>The JavaScript <code>try…catch</code> mechanism <strong>cannot</strong> be used to intercept errors generated by asynchronous APIs. A common mistake for beginners is to try to use <code>throw</code> inside an error-first callback:</p> <pre data-language="js">// THIS WILL NOT WORK:
const fs = require('fs');

try {
  fs.readFile('/some/file/that/does-not-exist', (err, data) =&gt; {
    // Mistaken assumption: throwing here...
    if (err) {
      throw err;
    }
  });
} catch (err) {
  // This will not catch the throw!
  console.error(err);
}
</pre> <p>This will not work because the callback function passed to <code>fs.readFile()</code> is called asynchronously. By the time the callback has been called, the surrounding code, including the <code>try…catch</code> block, will have already exited. Throwing an error inside the callback <strong>can crash the Node.js process</strong> in most cases. If <a href="../domain/">domains</a> are enabled, or a handler has been registered with <code>process.on('uncaughtException')</code>, such errors can be intercepted.</p> <h2 id="errors_class_error">Class: Error</h2> <p>A generic JavaScript <code>Error</code> object that does not denote any specific circumstance of why the error occurred. <code>Error</code> objects capture a "stack trace" detailing the point in the code at which the <code>Error</code> was instantiated, and may provide a text description of the error.</p> <p>All errors generated by Node.js, including all System and JavaScript errors, will either be instances of, or inherit from, the <code>Error</code> class.</p> <h3 id="errors_new_error_message">new Error(message)</h3> <ul> <li>
<code>message</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a>
</li> </ul> <p>Creates a new <code>Error</code> object and sets the <code>error.message</code> property to the provided text message. If an object is passed as <code>message</code>, the text message is generated by calling <code>message.toString()</code>. The <code>error.stack</code> property will represent the point in the code at which <code>new Error()</code> was called. Stack traces are dependent on <a href="https://github.com/v8/v8/wiki/Stack-Trace-API" target="_blank">V8's stack trace API</a>. Stack traces extend only to either (a) the beginning of <em>synchronous code execution</em>, or (b) the number of frames given by the property <code>Error.stackTraceLimit</code>, whichever is smaller.</p> <h3 id="errors_error_capturestacktrace_targetobject_constructoropt">Error.captureStackTrace(targetObject[, constructorOpt])</h3> <ul> <li>
<code>targetObject</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object" class="type" target="_blank">&lt;Object&gt;</a>
</li> <li>
<code>constructorOpt</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function" class="type" target="_blank">&lt;Function&gt;</a>
</li> </ul> <p>Creates a <code>.stack</code> property on <code>targetObject</code>, which when accessed returns a string representing the location in the code at which <code>Error.captureStackTrace()</code> was called.</p> <pre data-language="js">const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // Similar to `new Error().stack`
</pre> <p>The first line of the trace will be prefixed with <code>${myObject.name}: ${myObject.message}</code>.</p> <p>The optional <code>constructorOpt</code> argument accepts a function. If given, all frames above <code>constructorOpt</code>, including <code>constructorOpt</code>, will be omitted from the generated stack trace.</p> <p>The <code>constructorOpt</code> argument is useful for hiding implementation details of error generation from an end user. For instance:</p> <pre data-language="js">function MyError() {
  Error.captureStackTrace(this, MyError);
}

// Without passing MyError to captureStackTrace, the MyError
// frame would show up in the .stack property. By passing
// the constructor, we omit that frame, and retain all frames below it.
new MyError().stack;
</pre> <h3 id="errors_error_stacktracelimit">Error.stackTraceLimit</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type" target="_blank">&lt;number&gt;</a></li> </ul> <p>The <code>Error.stackTraceLimit</code> property specifies the number of stack frames collected by a stack trace (whether generated by <code>new Error().stack</code> or <code>Error.captureStackTrace(obj)</code>).</p> <p>The default value is <code>10</code> but may be set to any valid JavaScript number. Changes will affect any stack trace captured <em>after</em> the value has been changed.</p> <p>If set to a non-number value, or set to a negative number, stack traces will not capture any frames.</p> <h3 id="errors_error_code">error.code</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> <p>The <code>error.code</code> property is a string label that identifies the kind of error. <code>error.code</code> is the most stable way to identify an error. It will only change between major versions of Node.js. In contrast, <code>error.message</code> strings may change between any versions of Node.js. See <a href="#nodejs-error-codes">Node.js Error Codes</a> for details about specific codes.</p> <h3 id="errors_error_message">error.message</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> <p>The <code>error.message</code> property is the string description of the error as set by calling <code>new Error(message)</code>. The <code>message</code> passed to the constructor will also appear in the first line of the stack trace of the <code>Error</code>, however changing this property after the <code>Error</code> object is created <em>may not</em> change the first line of the stack trace (for example, when <code>error.stack</code> is read before this property is changed).</p> <pre data-language="js">const err = new Error('The message');
console.error(err.message);
// Prints: The message
</pre> <h3 id="errors_error_stack">error.stack</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> <p>The <code>error.stack</code> property is a string describing the point in the code at which the <code>Error</code> was instantiated.</p> <pre data-language="txt">Error: Things keep happening!
   at /home/gbusey/file.js:525:2
   at Frobnicator.refrobulate (/home/gbusey/business-logic.js:424:21)
   at Actor.&lt;anonymous&gt; (/home/gbusey/actors.js:400:8)
   at increaseSynergy (/home/gbusey/actors.js:701:6)
</pre> <p>The first line is formatted as <code>&lt;error class name&gt;: &lt;error message&gt;</code>, and is followed by a series of stack frames (each line beginning with "at "). Each frame describes a call site within the code that lead to the error being generated. V8 attempts to display a name for each function (by variable name, function name, or object method name), but occasionally it will not be able to find a suitable name. If V8 cannot determine a name for the function, only location information will be displayed for that frame. Otherwise, the determined function name will be displayed with location information appended in parentheses.</p> <p>Frames are only generated for JavaScript functions. If, for example, execution synchronously passes through a C++ addon function called <code>cheetahify</code> which itself calls a JavaScript function, the frame representing the <code>cheetahify</code> call will not be present in the stack traces:</p> <pre data-language="js">const cheetahify = require('./native-binding.node');

function makeFaster() {
  // `cheetahify()` *synchronously* calls speedy.
  cheetahify(function speedy() {
    throw new Error('oh no!');
  });
}

makeFaster();
// will throw:
//   /home/gbusey/file.js:6
//       throw new Error('oh no!');
//           ^
//   Error: oh no!
//       at speedy (/home/gbusey/file.js:6:11)
//       at makeFaster (/home/gbusey/file.js:5:3)
//       at Object.&lt;anonymous&gt; (/home/gbusey/file.js:10:1)
//       at Module._compile (module.js:456:26)
//       at Object.Module._extensions..js (module.js:474:10)
//       at Module.load (module.js:356:32)
//       at Function.Module._load (module.js:312:12)
//       at Function.Module.runMain (module.js:497:10)
//       at startup (node.js:119:16)
//       at node.js:906:3
</pre> <p>The location information will be one of:</p> <ul> <li>
<code>native</code>, if the frame represents a call internal to V8 (as in <code>[].forEach</code>).</li> <li>
<code>plain-filename.js:line:column</code>, if the frame represents a call internal to Node.js.</li> <li>
<code>/absolute/path/to/file.js:line:column</code>, if the frame represents a call in a user program, or its dependencies.</li> </ul> <p>The string representing the stack trace is lazily generated when the <code>error.stack</code> property is <strong>accessed</strong>.</p> <p>The number of frames captured by the stack trace is bounded by the smaller of <code>Error.stackTraceLimit</code> or the number of available frames on the current event loop tick.</p> <h2 id="errors_class_assertionerror">Class: AssertionError</h2> <p>A subclass of <code>Error</code> that indicates the failure of an assertion. For details, see <a href="../assert/#assert_class_assert_assertionerror"><code>Class: assert.AssertionError</code></a>.</p> <h2 id="errors_class_rangeerror">Class: RangeError</h2> <p>A subclass of <code>Error</code> that indicates that a provided argument was not within the set or range of acceptable values for a function; whether that is a numeric range, or outside the set of options for a given function parameter.</p> <pre data-language="js">require('net').connect(-1);
// Throws "RangeError: "port" option should be &gt;= 0 and &lt; 65536: -1"
</pre> <p>Node.js will generate and throw <code>RangeError</code> instances <em>immediately</em> as a form of argument validation.</p> <h2 id="errors_class_referenceerror">Class: ReferenceError</h2> <p>A subclass of <code>Error</code> that indicates that an attempt is being made to access a variable that is not defined. Such errors commonly indicate typos in code, or an otherwise broken program.</p> <p>While client code may generate and propagate these errors, in practice, only V8 will do so.</p> <pre data-language="js">doesNotExist;
// Throws ReferenceError, doesNotExist is not a variable in this program.
</pre> <p>Unless an application is dynamically generating and running code, <code>ReferenceError</code> instances should always be considered a bug in the code or its dependencies.</p> <h2 id="errors_class_syntaxerror">Class: SyntaxError</h2> <p>A subclass of <code>Error</code> that indicates that a program is not valid JavaScript. These errors may only be generated and propagated as a result of code evaluation. Code evaluation may happen as a result of <code>eval</code>, <code>Function</code>, <code>require</code>, or <a href="../vm/">vm</a>. These errors are almost always indicative of a broken program.</p> <pre data-language="js">try {
  require('vm').runInThisContext('binary ! isNotOk');
} catch (err) {
  // 'err' will be a SyntaxError.
}
</pre> <p><code>SyntaxError</code> instances are unrecoverable in the context that created them – they may only be caught by other contexts.</p> <h2 id="errors_class_systemerror">Class: SystemError</h2> <p>Node.js generates system errors when exceptions occur within its runtime environment. These usually occur when an application violates an operating system constraint. For example, a system error will occur if an application attempts to read a file that does not exist.</p> <ul> <li>
<code>address</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a> If present, the address to which a network connection failed</li> <li>
<code>code</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a> The string error code</li> <li>
<code>dest</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a> If present, the file path destination when reporting a file system error</li> <li>
<code>errno</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type" target="_blank">&lt;number&gt;</a> | <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a> The system-provided error number</li> <li>
<code>info</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object" class="type" target="_blank">&lt;Object&gt;</a> If present, extra details about the error condition</li> <li>
<code>message</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a> A system-provided human-readable description of the error</li> <li>
<code>path</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a> If present, the file path when reporting a file system error</li> <li>
<code>port</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type" target="_blank">&lt;number&gt;</a> If present, the network connection port that is not available</li> <li>
<code>syscall</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a> The name of the system call that triggered the error</li> </ul> <h3 id="errors_error_address">error.address</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> <p>If present, <code>error.address</code> is a string describing the address to which a network connection failed.</p> <h3 id="errors_error_code_1">error.code</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> <p>The <code>error.code</code> property is a string representing the error code.</p> <h3 id="errors_error_dest">error.dest</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> <p>If present, <code>error.dest</code> is the file path destination when reporting a file system error.</p> <h3 id="errors_error_errno">error.errno</h3> <ul> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a> | <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type" target="_blank">&lt;number&gt;</a>
</li> </ul> <p>The <code>error.errno</code> property is a number or a string. If it is a number, it is a negative value which corresponds to the error code defined in <a href="http://docs.libuv.org/en/v1.x/errors.html" target="_blank"><code>libuv Error handling</code></a>. See the libuv <code>errno.h</code> header file (<code>deps/uv/include/uv/errno.h</code> in the Node.js source tree) for details. In case of a string, it is the same as <code>error.code</code>.</p> <h3 id="errors_error_info">error.info</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object" class="type" target="_blank">&lt;Object&gt;</a></li> </ul> <p>If present, <code>error.info</code> is an object with details about the error condition.</p> <h3 id="errors_error_message_1">error.message</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> <p><code>error.message</code> is a system-provided human-readable description of the error.</p> <h3 id="errors_error_path">error.path</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> <p>If present, <code>error.path</code> is a string containing a relevant invalid pathname.</p> <h3 id="errors_error_port">error.port</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type" target="_blank">&lt;number&gt;</a></li> </ul> <p>If present, <code>error.port</code> is the network connection port that is not available.</p> <h3 id="errors_error_syscall">error.syscall</h3> <ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> <p>The <code>error.syscall</code> property is a string describing the <a href="http://man7.org/linux/man-pages/man2/syscalls.2.html" target="_blank">syscall</a> that failed.</p> <h3 id="errors_common_system_errors">Common System Errors</h3> <p>This is a list of system errors commonly-encountered when writing a Node.js program. For a comprehensive list, see the <a href="http://man7.org/linux/man-pages/man3/errno.3.html" target="_blank"><code>errno</code>(3) man page</a>.</p> <ul> <li> <p><code>EACCES</code> (Permission denied): An attempt was made to access a file in a way forbidden by its file access permissions.</p> </li> <li> <p><code>EADDRINUSE</code> (Address already in use): An attempt to bind a server (<a href="../net/"><code>net</code></a>, <a href="http" target="_blank"><code>http</code></a>, or <a href="https" target="_blank"><code>https</code></a>) to a local address failed due to another server on the local system already occupying that address.</p> </li> <li> <p><code>ECONNREFUSED</code> (Connection refused): No connection could be made because the target machine actively refused it. This usually results from trying to connect to a service that is inactive on the foreign host.</p> </li> <li> <p><code>ECONNRESET</code> (Connection reset by peer): A connection was forcibly closed by a peer. This normally results from a loss of the connection on the remote socket due to a timeout or reboot. Commonly encountered via the <a href="http" target="_blank"><code>http</code></a> and <a href="../net/"><code>net</code></a> modules.</p> </li> <li> <p><code>EEXIST</code> (File exists): An existing file was the target of an operation that required that the target not exist.</p> </li> <li> <p><code>EISDIR</code> (Is a directory): An operation expected a file, but the given pathname was a directory.</p> </li> <li> <p><code>EMFILE</code> (Too many open files in system): Maximum number of <a href="https://en.wikipedia.org/wiki/File_descriptor" target="_blank">file descriptors</a> allowable on the system has been reached, and requests for another descriptor cannot be fulfilled until at least one has been closed. This is encountered when opening many files at once in parallel, especially on systems (in particular, macOS) where there is a low file descriptor limit for processes. To remedy a low limit, run <code>ulimit -n 2048</code> in the same shell that will run the Node.js process.</p> </li> <li> <p><code>ENOENT</code> (No such file or directory): Commonly raised by <a href="../fs/"><code>fs</code></a> operations to indicate that a component of the specified pathname does not exist — no entity (file or directory) could be found by the given path.</p> </li> <li> <p><code>ENOTDIR</code> (Not a directory): A component of the given pathname existed, but was not a directory as expected. Commonly raised by <a href="../fs/#fs_fs_readdir_path_options_callback"><code>fs.readdir</code></a>.</p> </li> <li> <p><code>ENOTEMPTY</code> (Directory not empty): A directory with entries was the target of an operation that requires an empty directory — usually <a href="../fs/#fs_fs_unlink_path_callback"><code>fs.unlink</code></a>.</p> </li> <li> <p><code>ENOTFOUND</code> (DNS lookup failed): Indicates a DNS failure of either <code>EAI_NODATA</code> or <code>EAI_NONAME</code>. This is not a standard POSIX error.</p> </li> <li> <p><code>EPERM</code> (Operation not permitted): An attempt was made to perform an operation that requires elevated privileges.</p> </li> <li> <p><code>EPIPE</code> (Broken pipe): A write on a pipe, socket, or FIFO for which there is no process to read the data. Commonly encountered at the <a href="../net/"><code>net</code></a> and <a href="http" target="_blank"><code>http</code></a> layers, indicative that the remote side of the stream being written to has been closed.</p> </li> <li> <p><code>ETIMEDOUT</code> (Operation timed out): A connect or send request failed because the connected party did not properly respond after a period of time. Usually encountered by <a href="http" target="_blank"><code>http</code></a> or <a href="../net/"><code>net</code></a> — often a sign that a <code>socket.end()</code> was not properly called.</p> </li> </ul> <h2 id="errors_class_typeerror">Class: TypeError</h2> <p>A subclass of <code>Error</code> that indicates that a provided argument is not an allowable type. For example, passing a function to a parameter which expects a string would be considered a <code>TypeError</code>.</p> <pre data-language="js">require('url').parse(() =&gt; { });
// Throws TypeError, since it expected a string.
</pre> <p>Node.js will generate and throw <code>TypeError</code> instances <em>immediately</em> as a form of argument validation.</p> <h2 id="errors_exceptions_vs_errors">Exceptions vs. Errors</h2> <p>A JavaScript exception is a value that is thrown as a result of an invalid operation or as the target of a <code>throw</code> statement. While it is not required that these values are instances of <code>Error</code> or classes which inherit from <code>Error</code>, all exceptions thrown by Node.js or the JavaScript runtime <em>will</em> be instances of <code>Error</code>.</p> <p>Some exceptions are <em>unrecoverable</em> at the JavaScript layer. Such exceptions will <em>always</em> cause the Node.js process to crash. Examples include <code>assert()</code> checks or <code>abort()</code> calls in the C++ layer.</p> <h2 id="errors_openssl_errors">OpenSSL Errors</h2> <p>Errors originating in <code>crypto</code> or <code>tls</code> are of class <code>Error</code>, and in addition to the standard <code>.code</code> and <code>.message</code> properties, may have some additional OpenSSL-specific properties.</p> <h3 id="errors_error_opensslerrorstack">error.opensslErrorStack</h3> <p>An array of errors that can give context to where in the OpenSSL library an error originates from.</p> <h3 id="errors_error_function">error.function</h3> <p>The OpenSSL function the error originates in.</p> <h3 id="errors_error_library">error.library</h3> <p>The OpenSSL library the error originates in.</p> <h3 id="errors_error_reason">error.reason</h3> <p>A human-readable string describing the reason for the error.</p>  <h2 id="errors_node_js_error_codes">Node.js Error Codes</h2>  <h3 id="ERR_AMBIGUOUS_ARGUMENT">ERR_AMBIGUOUS_ARGUMENT</h3> <p>A function argument is being used in a way that suggests that the function signature may be misunderstood. This is thrown by the <code>assert</code> module when the <code>message</code> parameter in <code>assert.throws(block, message)</code> matches the error message thrown by <code>block</code> because that usage suggests that the user believes <code>message</code> is the expected message rather than the message the <code>AssertionError</code> will display if <code>block</code> does not throw.</p>  <h3 id="ERR_ARG_NOT_ITERABLE">ERR_ARG_NOT_ITERABLE</h3> <p>An iterable argument (i.e. a value that works with <code>for...of</code> loops) was required, but not provided to a Node.js API.</p>  <h3 id="ERR_ASSERTION">ERR_ASSERTION</h3> <p>A special type of error that can be triggered whenever Node.js detects an exceptional logic violation that should never occur. These are raised typically by the <code>assert</code> module.</p>  <h3 id="ERR_ASYNC_CALLBACK">ERR_ASYNC_CALLBACK</h3> <p>An attempt was made to register something that is not a function as an <code>AsyncHooks</code> callback.</p>  <h3 id="ERR_ASYNC_TYPE">ERR_ASYNC_TYPE</h3> <p>The type of an asynchronous resource was invalid. Users are also able to define their own types if using the public embedder API.</p>  <h3 id="ERR_BROTLI_COMPRESSION_FAILED">ERR_BROTLI_COMPRESSION_FAILED</h3> <p>Data passed to a Brotli stream was not successfully compressed.</p>  <h3 id="ERR_BROTLI_INVALID_PARAM">ERR_BROTLI_INVALID_PARAM</h3> <p>An invalid parameter key was passed during construction of a Brotli stream.</p>  <h3 id="ERR_BUFFER_CONTEXT_NOT_AVAILABLE">ERR_BUFFER_CONTEXT_NOT_AVAILABLE</h3> <p>An attempt was made to create a Node.js <code>Buffer</code> instance from addon or embedder code, while in a JS engine Context that is not associated with a Node.js instance. The data passed to the <code>Buffer</code> method will have been released by the time the method returns.</p> <p>When encountering this error, a possible alternative to creating a <code>Buffer</code> instance is to create a normal <code>Uint8Array</code>, which only differs in the prototype of the resulting object. <code>Uint8Array</code>s are generally accepted in all Node.js core APIs where <code>Buffer</code>s are; they are available in all Contexts.</p>  <h3 id="ERR_BUFFER_OUT_OF_BOUNDS">ERR_BUFFER_OUT_OF_BOUNDS</h3> <p>An operation outside the bounds of a <code>Buffer</code> was attempted.</p>  <h3 id="ERR_BUFFER_TOO_LARGE">ERR_BUFFER_TOO_LARGE</h3> <p>An attempt has been made to create a <code>Buffer</code> larger than the maximum allowed size.</p>  <h3 id="ERR_CANNOT_WATCH_SIGINT">ERR_CANNOT_WATCH_SIGINT</h3> <p>Node.js was unable to watch for the <code>SIGINT</code> signal.</p>  <h3 id="ERR_CHILD_CLOSED_BEFORE_REPLY">ERR_CHILD_CLOSED_BEFORE_REPLY</h3> <p>A child process was closed before the parent received a reply.</p>  <h3 id="ERR_CHILD_PROCESS_IPC_REQUIRED">ERR_CHILD_PROCESS_IPC_REQUIRED</h3> <p>Used when a child process is being forked without specifying an IPC channel.</p>  <h3 id="ERR_CHILD_PROCESS_STDIO_MAXBUFFER">ERR_CHILD_PROCESS_STDIO_MAXBUFFER</h3> <p>Used when the main process is trying to read data from the child process's STDERR/STDOUT, and the data's length is longer than the <code>maxBuffer</code> option.</p>  <h3 id="ERR_CONSOLE_WRITABLE_STREAM">ERR_CONSOLE_WRITABLE_STREAM</h3> <p><code>Console</code> was instantiated without <code>stdout</code> stream, or <code>Console</code> has a non-writable <code>stdout</code> or <code>stderr</code> stream.</p>  <h3 id="ERR_CONSTRUCT_CALL_REQUIRED">ERR_CONSTRUCT_CALL_REQUIRED</h3> <p>A constructor for a class was called without <code>new</code>.</p>  <h3 id="ERR_CONSTRUCT_CALL_INVALID">ERR_CONSTRUCT_CALL_INVALID</h3>  <p>A class constructor was called that is not callable.</p>  <h3 id="ERR_CPU_USAGE">ERR_CPU_USAGE</h3> <p>The native call from <code>process.cpuUsage</code> could not be processed.</p>  <h3 id="ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED">ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED</h3> <p>A client certificate engine was requested that is not supported by the version of OpenSSL being used.</p>  <h3 id="ERR_CRYPTO_ECDH_INVALID_FORMAT">ERR_CRYPTO_ECDH_INVALID_FORMAT</h3> <p>An invalid value for the <code>format</code> argument was passed to the <code>crypto.ECDH()</code> class <code>getPublicKey()</code> method.</p>  <h3 id="ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY">ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY</h3> <p>An invalid value for the <code>key</code> argument has been passed to the <code>crypto.ECDH()</code> class <code>computeSecret()</code> method. It means that the public key lies outside of the elliptic curve.</p>  <h3 id="ERR_CRYPTO_ENGINE_UNKNOWN">ERR_CRYPTO_ENGINE_UNKNOWN</h3> <p>An invalid crypto engine identifier was passed to <a href="../crypto/#crypto_crypto_setengine_engine_flags"><code>require('crypto').setEngine()</code></a>.</p>  <h3 id="ERR_CRYPTO_FIPS_FORCED">ERR_CRYPTO_FIPS_FORCED</h3> <p>The <a href="../cli/#cli_force_fips"><code>--force-fips</code></a> command-line argument was used but there was an attempt to enable or disable FIPS mode in the <code>crypto</code> module.</p>  <h3 id="ERR_CRYPTO_FIPS_UNAVAILABLE">ERR_CRYPTO_FIPS_UNAVAILABLE</h3> <p>An attempt was made to enable or disable FIPS mode, but FIPS mode was not available.</p>  <h3 id="ERR_CRYPTO_HASH_DIGEST_NO_UTF16">ERR_CRYPTO_HASH_DIGEST_NO_UTF16</h3> <p>The UTF-16 encoding was used with <a href="../crypto/#crypto_hash_digest_encoding"><code>hash.digest()</code></a>. While the <code>hash.digest()</code> method does allow an <code>encoding</code> argument to be passed in, causing the method to return a string rather than a <code>Buffer</code>, the UTF-16 encoding (e.g. <code>ucs</code> or <code>utf16le</code>) is not supported.</p>  <h3 id="ERR_CRYPTO_HASH_FINALIZED">ERR_CRYPTO_HASH_FINALIZED</h3> <p><a href="../crypto/#crypto_hash_digest_encoding"><code>hash.digest()</code></a> was called multiple times. The <code>hash.digest()</code> method must be called no more than one time per instance of a <code>Hash</code> object.</p>  <h3 id="ERR_CRYPTO_HASH_UPDATE_FAILED">ERR_CRYPTO_HASH_UPDATE_FAILED</h3> <p><a href="../crypto/#crypto_hash_update_data_inputencoding"><code>hash.update()</code></a> failed for any reason. This should rarely, if ever, happen.</p>  <h3 id="ERR_CRYPTO_INCOMPATIBLE_KEY_OPTIONS">ERR_CRYPTO_INCOMPATIBLE_KEY_OPTIONS</h3> <p>The selected public or private key encoding is incompatible with other options.</p>  <h3 id="ERR_CRYPTO_INVALID_DIGEST">ERR_CRYPTO_INVALID_DIGEST</h3> <p>An invalid <a href="../crypto/#crypto_crypto_gethashes">crypto digest algorithm</a> was specified.</p>  <h3 id="ERR_CRYPTO_INVALID_KEY_OBJECT_TYPE">ERR_CRYPTO_INVALID_KEY_OBJECT_TYPE</h3> <p>The given crypto key object's type is invalid for the attempted operation.</p>  <h3 id="ERR_CRYPTO_INVALID_STATE">ERR_CRYPTO_INVALID_STATE</h3> <p>A crypto method was used on an object that was in an invalid state. For instance, calling <a href="../crypto/#crypto_cipher_getauthtag"><code>cipher.getAuthTag()</code></a> before calling <code>cipher.final()</code>.</p>  <h3 id="ERR_CRYPTO_PBKDF2_ERROR">ERR_CRYPTO_PBKDF2_ERROR</h3> <p>The PBKDF2 algorithm failed for unspecified reasons. OpenSSL does not provide more details and therefore neither does Node.js.</p>  <h3 id="ERR_CRYPTO_SCRYPT_INVALID_PARAMETER">ERR_CRYPTO_SCRYPT_INVALID_PARAMETER</h3> <p>One or more <a href="../crypto/#crypto_crypto_scrypt_password_salt_keylen_options_callback"><code>crypto.scrypt()</code></a> or <a href="../crypto/#crypto_crypto_scryptsync_password_salt_keylen_options"><code>crypto.scryptSync()</code></a> parameters are outside their legal range.</p>  <h3 id="ERR_CRYPTO_SCRYPT_NOT_SUPPORTED">ERR_CRYPTO_SCRYPT_NOT_SUPPORTED</h3> <p>Node.js was compiled without <code>scrypt</code> support. Not possible with the official release binaries but can happen with custom builds, including distro builds.</p>  <h3 id="ERR_CRYPTO_SIGN_KEY_REQUIRED">ERR_CRYPTO_SIGN_KEY_REQUIRED</h3> <p>A signing <code>key</code> was not provided to the <a href="../crypto/#crypto_sign_sign_privatekey_outputencoding"><code>sign.sign()</code></a> method.</p>  <h3 id="ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH">ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH</h3> <p><a href="../crypto/#crypto_crypto_timingsafeequal_a_b"><code>crypto.timingSafeEqual()</code></a> was called with <code>Buffer</code>, <code>TypedArray</code>, or <code>DataView</code> arguments of different lengths.</p>  <h3 id="ERR_DNS_SET_SERVERS_FAILED">ERR_DNS_SET_SERVERS_FAILED</h3> <p><code>c-ares</code> failed to set the DNS server.</p>  <h3 id="ERR_DOMAIN_CALLBACK_NOT_AVAILABLE">ERR_DOMAIN_CALLBACK_NOT_AVAILABLE</h3> <p>The <code>domain</code> module was not usable since it could not establish the required error handling hooks, because <a href="../process/#process_process_setuncaughtexceptioncapturecallback_fn"><code>process.setUncaughtExceptionCaptureCallback()</code></a> had been called at an earlier point in time.</p>  <h3 id="ERR_DOMAIN_CANNOT_SET_UNCAUGHT_EXCEPTION_CAPTURE">ERR_DOMAIN_CANNOT_SET_UNCAUGHT_EXCEPTION_CAPTURE</h3> <p><a href="../process/#process_process_setuncaughtexceptioncapturecallback_fn"><code>process.setUncaughtExceptionCaptureCallback()</code></a> could not be called because the <code>domain</code> module has been loaded at an earlier point in time.</p> <p>The stack trace is extended to include the point in time at which the <code>domain</code> module had been loaded.</p>  <h3 id="ERR_ENCODING_INVALID_ENCODED_DATA">ERR_ENCODING_INVALID_ENCODED_DATA</h3> <p>Data provided to <code>TextDecoder()</code> API was invalid according to the encoding provided.</p>  <h3 id="ERR_ENCODING_NOT_SUPPORTED">ERR_ENCODING_NOT_SUPPORTED</h3> <p>Encoding provided to <code>TextDecoder()</code> API was not one of the <a href="../util/#util_whatwg_supported_encodings">WHATWG Supported Encodings</a>.</p>  <h3 id="ERR_FALSY_VALUE_REJECTION">ERR_FALSY_VALUE_REJECTION</h3> <p>A <code>Promise</code> that was callbackified via <code>util.callbackify()</code> was rejected with a falsy value.</p>  <h3 id="ERR_FS_FILE_TOO_LARGE">ERR_FS_FILE_TOO_LARGE</h3> <p>An attempt has been made to read a file whose size is larger than the maximum allowed size for a <code>Buffer</code>.</p>  <h3 id="ERR_FS_INVALID_SYMLINK_TYPE">ERR_FS_INVALID_SYMLINK_TYPE</h3> <p>An invalid symlink type was passed to the <a href="../fs/#fs_fs_symlink_target_path_type_callback"><code>fs.symlink()</code></a> or <a href="../fs/#fs_fs_symlinksync_target_path_type"><code>fs.symlinkSync()</code></a> methods.</p>  <h3 id="ERR_HTTP_HEADERS_SENT">ERR_HTTP_HEADERS_SENT</h3> <p>An attempt was made to add more headers after the headers had already been sent.</p>  <h3 id="ERR_HTTP_INVALID_HEADER_VALUE">ERR_HTTP_INVALID_HEADER_VALUE</h3> <p>An invalid HTTP header value was specified.</p>  <h3 id="ERR_HTTP_INVALID_STATUS_CODE">ERR_HTTP_INVALID_STATUS_CODE</h3> <p>Status code was outside the regular status code range (100-999).</p>  <h3 id="ERR_HTTP_TRAILER_INVALID">ERR_HTTP_TRAILER_INVALID</h3> <p>The <code>Trailer</code> header was set even though the transfer encoding does not support that.</p>  <h3 id="ERR_HTTP2_ALTSVC_INVALID_ORIGIN">ERR_HTTP2_ALTSVC_INVALID_ORIGIN</h3> <p>HTTP/2 ALTSVC frames require a valid origin.</p>  <h3 id="ERR_HTTP2_ALTSVC_LENGTH">ERR_HTTP2_ALTSVC_LENGTH</h3> <p>HTTP/2 ALTSVC frames are limited to a maximum of 16,382 payload bytes.</p>  <h3 id="ERR_HTTP2_CONNECT_AUTHORITY">ERR_HTTP2_CONNECT_AUTHORITY</h3> <p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:authority</code> pseudo-header is required.</p>  <h3 id="ERR_HTTP2_CONNECT_PATH">ERR_HTTP2_CONNECT_PATH</h3> <p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:path</code> pseudo-header is forbidden.</p>  <h3 id="ERR_HTTP2_CONNECT_SCHEME">ERR_HTTP2_CONNECT_SCHEME</h3> <p>For HTTP/2 requests using the <code>CONNECT</code> method, the <code>:scheme</code> pseudo-header is forbidden.</p>  <h3 id="ERR_HTTP2_ERROR">ERR_HTTP2_ERROR</h3> <p>A non-specific HTTP/2 error has occurred.</p>  <h3 id="ERR_HTTP2_GOAWAY_SESSION">ERR_HTTP2_GOAWAY_SESSION</h3> <p>New HTTP/2 Streams may not be opened after the <code>Http2Session</code> has received a <code>GOAWAY</code> frame from the connected peer.</p>  <h3 id="ERR_HTTP2_HEADERS_AFTER_RESPOND">ERR_HTTP2_HEADERS_AFTER_RESPOND</h3> <p>An additional headers was specified after an HTTP/2 response was initiated.</p>  <h3 id="ERR_HTTP2_HEADERS_SENT">ERR_HTTP2_HEADERS_SENT</h3> <p>An attempt was made to send multiple response headers.</p>  <h3 id="ERR_HTTP2_HEADER_SINGLE_VALUE">ERR_HTTP2_HEADER_SINGLE_VALUE</h3> <p>Multiple values were provided for an HTTP/2 header field that was required to have only a single value.</p>  <h3 id="ERR_HTTP2_INFO_STATUS_NOT_ALLOWED">ERR_HTTP2_INFO_STATUS_NOT_ALLOWED</h3> <p>Informational HTTP status codes (<code>1xx</code>) may not be set as the response status code on HTTP/2 responses.</p>  <h3 id="ERR_HTTP2_INVALID_CONNECTION_HEADERS">ERR_HTTP2_INVALID_CONNECTION_HEADERS</h3> <p>HTTP/1 connection specific headers are forbidden to be used in HTTP/2 requests and responses.</p>  <h3 id="ERR_HTTP2_INVALID_HEADER_VALUE">ERR_HTTP2_INVALID_HEADER_VALUE</h3> <p>An invalid HTTP/2 header value was specified.</p>  <h3 id="ERR_HTTP2_INVALID_INFO_STATUS">ERR_HTTP2_INVALID_INFO_STATUS</h3> <p>An invalid HTTP informational status code has been specified. Informational status codes must be an integer between <code>100</code> and <code>199</code> (inclusive).</p>  <h3 id="ERR_HTTP2_INVALID_ORIGIN">ERR_HTTP2_INVALID_ORIGIN</h3> <p>HTTP/2 <code>ORIGIN</code> frames require a valid origin.</p>  <h3 id="ERR_HTTP2_INVALID_PACKED_SETTINGS_LENGTH">ERR_HTTP2_INVALID_PACKED_SETTINGS_LENGTH</h3> <p>Input <code>Buffer</code> and <code>Uint8Array</code> instances passed to the <code>http2.getUnpackedSettings()</code> API must have a length that is a multiple of six.</p>  <h3 id="ERR_HTTP2_INVALID_PSEUDOHEADER">ERR_HTTP2_INVALID_PSEUDOHEADER</h3> <p>Only valid HTTP/2 pseudoheaders (<code>:status</code>, <code>:path</code>, <code>:authority</code>, <code>:scheme</code>, and <code>:method</code>) may be used.</p>  <h3 id="ERR_HTTP2_INVALID_SESSION">ERR_HTTP2_INVALID_SESSION</h3> <p>An action was performed on an <code>Http2Session</code> object that had already been destroyed.</p>  <h3 id="ERR_HTTP2_INVALID_SETTING_VALUE">ERR_HTTP2_INVALID_SETTING_VALUE</h3> <p>An invalid value has been specified for an HTTP/2 setting.</p>  <h3 id="ERR_HTTP2_INVALID_STREAM">ERR_HTTP2_INVALID_STREAM</h3> <p>An operation was performed on a stream that had already been destroyed.</p>  <h3 id="ERR_HTTP2_MAX_PENDING_SETTINGS_ACK">ERR_HTTP2_MAX_PENDING_SETTINGS_ACK</h3> <p>Whenever an HTTP/2 <code>SETTINGS</code> frame is sent to a connected peer, the peer is required to send an acknowledgment that it has received and applied the new <code>SETTINGS</code>. By default, a maximum number of unacknowledged <code>SETTINGS</code> frames may be sent at any given time. This error code is used when that limit has been reached.</p>  <h3 id="ERR_HTTP2_NESTED_PUSH">ERR_HTTP2_NESTED_PUSH</h3> <p>An attempt was made to initiate a new push stream from within a push stream. Nested push streams are not permitted.</p>  <h3 id="ERR_HTTP2_NO_SOCKET_MANIPULATION">ERR_HTTP2_NO_SOCKET_MANIPULATION</h3> <p>An attempt was made to directly manipulate (read, write, pause, resume, etc.) a socket attached to an <code>Http2Session</code>.</p>  <h3 id="ERR_HTTP2_ORIGIN_LENGTH">ERR_HTTP2_ORIGIN_LENGTH</h3> <p>HTTP/2 <code>ORIGIN</code> frames are limited to a length of 16382 bytes.</p>  <h3 id="ERR_HTTP2_OUT_OF_STREAMS">ERR_HTTP2_OUT_OF_STREAMS</h3> <p>The number of streams created on a single HTTP/2 session reached the maximum limit.</p>  <h3 id="ERR_HTTP2_PAYLOAD_FORBIDDEN">ERR_HTTP2_PAYLOAD_FORBIDDEN</h3> <p>A message payload was specified for an HTTP response code for which a payload is forbidden.</p>  <h3 id="ERR_HTTP2_PING_CANCEL">ERR_HTTP2_PING_CANCEL</h3> <p>An HTTP/2 ping was canceled.</p>  <h3 id="ERR_HTTP2_PING_LENGTH">ERR_HTTP2_PING_LENGTH</h3> <p>HTTP/2 ping payloads must be exactly 8 bytes in length.</p>  <h3 id="ERR_HTTP2_PSEUDOHEADER_NOT_ALLOWED">ERR_HTTP2_PSEUDOHEADER_NOT_ALLOWED</h3> <p>An HTTP/2 pseudo-header has been used inappropriately. Pseudo-headers are header key names that begin with the <code>:</code> prefix.</p>  <h3 id="ERR_HTTP2_PUSH_DISABLED">ERR_HTTP2_PUSH_DISABLED</h3> <p>An attempt was made to create a push stream, which had been disabled by the client.</p>  <h3 id="ERR_HTTP2_SEND_FILE">ERR_HTTP2_SEND_FILE</h3> <p>An attempt was made to use the <code>Http2Stream.prototype.responseWithFile()</code> API to send a directory.</p>  <h3 id="ERR_HTTP2_SEND_FILE_NOSEEK">ERR_HTTP2_SEND_FILE_NOSEEK</h3> <p>An attempt was made to use the <code>Http2Stream.prototype.responseWithFile()</code> API to send something other than a regular file, but <code>offset</code> or <code>length</code> options were provided.</p>  <h3 id="ERR_HTTP2_SESSION_ERROR">ERR_HTTP2_SESSION_ERROR</h3> <p>The <code>Http2Session</code> closed with a non-zero error code.</p>  <h3 id="ERR_HTTP2_SETTINGS_CANCEL">ERR_HTTP2_SETTINGS_CANCEL</h3> <p>The <code>Http2Session</code> settings canceled.</p>  <h3 id="ERR_HTTP2_SOCKET_BOUND">ERR_HTTP2_SOCKET_BOUND</h3> <p>An attempt was made to connect a <code>Http2Session</code> object to a <code>net.Socket</code> or <code>tls.TLSSocket</code> that had already been bound to another <code>Http2Session</code> object.</p>  <h3 id="ERR_HTTP2_SOCKET_UNBOUND">ERR_HTTP2_SOCKET_UNBOUND</h3> <p>An attempt was made to use the <code>socket</code> property of an <code>Http2Session</code> that has already been closed.</p>  <h3 id="ERR_HTTP2_STATUS_101">ERR_HTTP2_STATUS_101</h3> <p>Use of the <code>101</code> Informational status code is forbidden in HTTP/2.</p>  <h3 id="ERR_HTTP2_STATUS_INVALID">ERR_HTTP2_STATUS_INVALID</h3> <p>An invalid HTTP status code has been specified. Status codes must be an integer between <code>100</code> and <code>599</code> (inclusive).</p>  <h3 id="ERR_HTTP2_STREAM_CANCEL">ERR_HTTP2_STREAM_CANCEL</h3> <p>An <code>Http2Stream</code> was destroyed before any data was transmitted to the connected peer.</p>  <h3 id="ERR_HTTP2_STREAM_ERROR">ERR_HTTP2_STREAM_ERROR</h3> <p>A non-zero error code was been specified in an <code>RST_STREAM</code> frame.</p>  <h3 id="ERR_HTTP2_STREAM_SELF_DEPENDENCY">ERR_HTTP2_STREAM_SELF_DEPENDENCY</h3> <p>When setting the priority for an HTTP/2 stream, the stream may be marked as a dependency for a parent stream. This error code is used when an attempt is made to mark a stream and dependent of itself.</p>  <h3 id="ERR_HTTP2_TRAILERS_ALREADY_SENT">ERR_HTTP2_TRAILERS_ALREADY_SENT</h3> <p>Trailing headers have already been sent on the <code>Http2Stream</code>.</p>  <h3 id="ERR_HTTP2_TRAILERS_NOT_READY">ERR_HTTP2_TRAILERS_NOT_READY</h3> <p>The <code>http2stream.sendTrailers()</code> method cannot be called until after the <code>'wantTrailers'</code> event is emitted on an <code>Http2Stream</code> object. The <code>'wantTrailers'</code> event will only be emitted if the <code>waitForTrailers</code> option is set for the <code>Http2Stream</code>.</p>  <h3 id="ERR_HTTP2_UNSUPPORTED_PROTOCOL">ERR_HTTP2_UNSUPPORTED_PROTOCOL</h3> <p><code>http2.connect()</code> was passed a URL that uses any protocol other than <code>http:</code> or <code>https:</code>.</p>  <h3 id="ERR_INTERNAL_ASSERTION">ERR_INTERNAL_ASSERTION</h3> <p>There was a bug in Node.js or incorrect usage of Node.js internals. To fix the error, open an issue at <a href="https://github.com/nodejs/node/issues" target="_blank">https://github.com/nodejs/node/issues</a>.</p>  <h3 id="ERR_INCOMPATIBLE_OPTION_PAIR">ERR_INCOMPATIBLE_OPTION_PAIR</h3> <p>An option pair is incompatible with each other and can not be used at the same time.</p>  <h3 id="ERR_INPUT_TYPE_NOT_ALLOWED">ERR_INPUT_TYPE_NOT_ALLOWED</h3> 
<div class="api_stability api_stability_1">
<a href="https://nodejs.org/dist/latest-v12.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 1</a> - Experimental</div>
 <p>The <code>--input-type</code> flag was used to attempt to execute a file. This flag can only be used with input via <code>--eval</code>, <code>--print</code> or <code>STDIN</code>.</p>  <h3 id="ERR_INSPECTOR_ALREADY_CONNECTED">ERR_INSPECTOR_ALREADY_CONNECTED</h3> <p>While using the <code>inspector</code> module, an attempt was made to connect when the inspector was already connected.</p>  <h3 id="ERR_INSPECTOR_CLOSED">ERR_INSPECTOR_CLOSED</h3> <p>While using the <code>inspector</code> module, an attempt was made to use the inspector after the session had already closed.</p>  <h3 id="ERR_INSPECTOR_COMMAND">ERR_INSPECTOR_COMMAND</h3> <p>An error occurred while issuing a command via the <code>inspector</code> module.</p>  <h3 id="ERR_INSPECTOR_NOT_ACTIVE">ERR_INSPECTOR_NOT_ACTIVE</h3> <p>The <code>inspector</code> is not active when <code>inspector.waitForDebugger()</code> is called.</p>  <h3 id="ERR_INSPECTOR_NOT_AVAILABLE">ERR_INSPECTOR_NOT_AVAILABLE</h3> <p>The <code>inspector</code> module is not available for use.</p>  <h3 id="ERR_INSPECTOR_NOT_CONNECTED">ERR_INSPECTOR_NOT_CONNECTED</h3> <p>While using the <code>inspector</code> module, an attempt was made to use the inspector before it was connected.</p>  <h3 id="ERR_INVALID_ADDRESS_FAMILY">ERR_INVALID_ADDRESS_FAMILY</h3> <p>The provided address family is not understood by the Node.js API.</p>  <h3 id="ERR_INVALID_ARG_TYPE">ERR_INVALID_ARG_TYPE</h3> <p>An argument of the wrong type was passed to a Node.js API.</p>  <h3 id="ERR_INVALID_ARG_VALUE">ERR_INVALID_ARG_VALUE</h3> <p>An invalid or unsupported value was passed for a given argument.</p>  <h3 id="ERR_INVALID_ASYNC_ID">ERR_INVALID_ASYNC_ID</h3> <p>An invalid <code>asyncId</code> or <code>triggerAsyncId</code> was passed using <code>AsyncHooks</code>. An id less than -1 should never happen.</p>  <h3 id="ERR_INVALID_BUFFER_SIZE">ERR_INVALID_BUFFER_SIZE</h3> <p>A swap was performed on a <code>Buffer</code> but its size was not compatible with the operation.</p>  <h3 id="ERR_INVALID_CALLBACK">ERR_INVALID_CALLBACK</h3> <p>A callback function was required but was not been provided to a Node.js API.</p>  <h3 id="ERR_INVALID_CHAR">ERR_INVALID_CHAR</h3> <p>Invalid characters were detected in headers.</p>  <h3 id="ERR_INVALID_CURSOR_POS">ERR_INVALID_CURSOR_POS</h3> <p>A cursor on a given stream cannot be moved to a specified row without a specified column.</p>  <h3 id="ERR_INVALID_FD">ERR_INVALID_FD</h3> <p>A file descriptor ('fd') was not valid (e.g. it was a negative value).</p>  <h3 id="ERR_INVALID_FD_TYPE">ERR_INVALID_FD_TYPE</h3> <p>A file descriptor ('fd') type was not valid.</p>  <h3 id="ERR_INVALID_FILE_URL_HOST">ERR_INVALID_FILE_URL_HOST</h3> <p>A Node.js API that consumes <code>file:</code> URLs (such as certain functions in the <a href="../fs/"><code>fs</code></a> module) encountered a file URL with an incompatible host. This situation can only occur on Unix-like systems where only <code>localhost</code> or an empty host is supported.</p>  <h3 id="ERR_INVALID_FILE_URL_PATH">ERR_INVALID_FILE_URL_PATH</h3> <p>A Node.js API that consumes <code>file:</code> URLs (such as certain functions in the <a href="../fs/"><code>fs</code></a> module) encountered a file URL with an incompatible path. The exact semantics for determining whether a path can be used is platform-dependent.</p>  <h3 id="ERR_INVALID_HANDLE_TYPE">ERR_INVALID_HANDLE_TYPE</h3> <p>An attempt was made to send an unsupported "handle" over an IPC communication channel to a child process. See <a href="../child_process/#child_process_subprocess_send_message_sendhandle_options_callback"><code>subprocess.send()</code></a> and <a href="../process/#process_process_send_message_sendhandle_options_callback"><code>process.send()</code></a> for more information.</p>  <h3 id="ERR_INVALID_HTTP_TOKEN">ERR_INVALID_HTTP_TOKEN</h3> <p>An invalid HTTP token was supplied.</p>  <h3 id="ERR_INVALID_IP_ADDRESS">ERR_INVALID_IP_ADDRESS</h3> <p>An IP address is not valid.</p>  <h3 id="ERR_INVALID_OPT_VALUE">ERR_INVALID_OPT_VALUE</h3> <p>An invalid or unexpected value was passed in an options object.</p>  <h3 id="ERR_INVALID_OPT_VALUE_ENCODING">ERR_INVALID_OPT_VALUE_ENCODING</h3> <p>An invalid or unknown file encoding was passed.</p>  <h3 id="ERR_INVALID_PACKAGE_CONFIG">ERR_INVALID_PACKAGE_CONFIG</h3> <p>An invalid <code>package.json</code> file was found which failed parsing.</p>  <h3 id="ERR_INVALID_PERFORMANCE_MARK">ERR_INVALID_PERFORMANCE_MARK</h3> <p>While using the Performance Timing API (<code>perf_hooks</code>), a performance mark is invalid.</p>  <h3 id="ERR_INVALID_PROTOCOL">ERR_INVALID_PROTOCOL</h3> <p>An invalid <code>options.protocol</code> was passed to <code>http.request()</code>.</p>  <h3 id="ERR_INVALID_REPL_EVAL_CONFIG">ERR_INVALID_REPL_EVAL_CONFIG</h3> <p>Both <code>breakEvalOnSigint</code> and <code>eval</code> options were set in the <a href="../repl/"><code>REPL</code></a> config, which is not supported.</p>  <h3 id="ERR_INVALID_REPL_INPUT">ERR_INVALID_REPL_INPUT</h3> <p>The input may not be used in the <a href="../repl/"><code>REPL</code></a>. All prohibited inputs are documented in the <a href="../repl/"><code>REPL</code></a>'s documentation.</p>  <h3 id="ERR_INVALID_RETURN_PROPERTY">ERR_INVALID_RETURN_PROPERTY</h3> <p>Thrown in case a function option does not provide a valid value for one of its returned object properties on execution.</p>  <h3 id="ERR_INVALID_RETURN_PROPERTY_VALUE">ERR_INVALID_RETURN_PROPERTY_VALUE</h3> <p>Thrown in case a function option does not provide an expected value type for one of its returned object properties on execution.</p>  <h3 id="ERR_INVALID_RETURN_VALUE">ERR_INVALID_RETURN_VALUE</h3> <p>Thrown in case a function option does not return an expected value type on execution, such as when a function is expected to return a promise.</p>  <h3 id="ERR_INVALID_SYNC_FORK_INPUT">ERR_INVALID_SYNC_FORK_INPUT</h3> <p>A <code>Buffer</code>, <code>TypedArray</code>, <code>DataView</code> or <code>string</code> was provided as stdio input to an asynchronous fork. See the documentation for the <a href="../child_process/"><code>child_process</code></a> module for more information.</p>  <h3 id="ERR_INVALID_THIS">ERR_INVALID_THIS</h3> <p>A Node.js API function was called with an incompatible <code>this</code> value.</p> <pre data-language="js">const urlSearchParams = new URLSearchParams('foo=bar&amp;baz=new');

const buf = Buffer.alloc(1);
urlSearchParams.has.call(buf, 'foo');
// Throws a TypeError with code 'ERR_INVALID_THIS'
</pre>  <h3 id="ERR_INVALID_TRANSFER_OBJECT">ERR_INVALID_TRANSFER_OBJECT</h3> <p>An invalid transfer object was passed to <code>postMessage()</code>.</p>  <h3 id="ERR_INVALID_TUPLE">ERR_INVALID_TUPLE</h3> <p>An element in the <code>iterable</code> provided to the <a href="../url/#url_the_whatwg_url_api">WHATWG</a> <a href="../url/#url_constructor_new_urlsearchparams_iterable"><code>URLSearchParams</code> constructor</a> did not represent a <code>[name, value]</code> tuple – that is, if an element is not iterable, or does not consist of exactly two elements.</p>  <h3 id="ERR_INVALID_URI">ERR_INVALID_URI</h3> <p>An invalid URI was passed.</p>  <h3 id="ERR_INVALID_URL">ERR_INVALID_URL</h3> <p>An invalid URL was passed to the <a href="../url/#url_the_whatwg_url_api">WHATWG</a> <a href="../url/#url_constructor_new_url_input_base"><code>URL</code> constructor</a> to be parsed. The thrown error object typically has an additional property <code>'input'</code> that contains the URL that failed to parse.</p>  <h3 id="ERR_INVALID_URL_SCHEME">ERR_INVALID_URL_SCHEME</h3> <p>An attempt was made to use a URL of an incompatible scheme (protocol) for a specific purpose. It is only used in the <a href="../url/#url_the_whatwg_url_api">WHATWG URL API</a> support in the <a href="../fs/"><code>fs</code></a> module (which only accepts URLs with <code>'file'</code> scheme), but may be used in other Node.js APIs as well in the future.</p>  <h3 id="ERR_IPC_CHANNEL_CLOSED">ERR_IPC_CHANNEL_CLOSED</h3> <p>An attempt was made to use an IPC communication channel that was already closed.</p>  <h3 id="ERR_IPC_DISCONNECTED">ERR_IPC_DISCONNECTED</h3> <p>An attempt was made to disconnect an IPC communication channel that was already disconnected. See the documentation for the <a href="../child_process/"><code>child_process</code></a> module for more information.</p>  <h3 id="ERR_IPC_ONE_PIPE">ERR_IPC_ONE_PIPE</h3> <p>An attempt was made to create a child Node.js process using more than one IPC communication channel. See the documentation for the <a href="../child_process/"><code>child_process</code></a> module for more information.</p>  <h3 id="ERR_IPC_SYNC_FORK">ERR_IPC_SYNC_FORK</h3> <p>An attempt was made to open an IPC communication channel with a synchronously forked Node.js process. See the documentation for the <a href="../child_process/"><code>child_process</code></a> module for more information.</p>  <h3 id="ERR_MANIFEST_ASSERT_INTEGRITY">ERR_MANIFEST_ASSERT_INTEGRITY</h3> <p>An attempt was made to load a resource, but the resource did not match the integrity defined by the policy manifest. See the documentation for <a href="../policy/">policy</a> manifests for more information.</p>  <h3 id="ERR_MANIFEST_DEPENDENCY_MISSING">ERR_MANIFEST_DEPENDENCY_MISSING</h3> <p>An attempt was made to load a resource, but the resource was not listed as a dependency from the location that attempted to load it. See the documentation for <a href="../policy/">policy</a> manifests for more information.</p>  <h3 id="ERR_MANIFEST_INTEGRITY_MISMATCH">ERR_MANIFEST_INTEGRITY_MISMATCH</h3> <p>An attempt was made to load a policy manifest, but the manifest had multiple entries for a resource which did not match each other. Update the manifest entries to match in order to resolve this error. See the documentation for <a href="../policy/">policy</a> manifests for more information.</p>  <h3 id="ERR_MANIFEST_INVALID_RESOURCE_FIELD">ERR_MANIFEST_INVALID_RESOURCE_FIELD</h3> <p>A policy manifest resource had an invalid value for one of its fields. Update the manifest entry to match in order to resolve this error. See the documentation for <a href="../policy/">policy</a> manifests for more information.</p>  <h3 id="ERR_MANIFEST_PARSE_POLICY">ERR_MANIFEST_PARSE_POLICY</h3> <p>An attempt was made to load a policy manifest, but the manifest was unable to be parsed. See the documentation for <a href="../policy/">policy</a> manifests for more information.</p>  <h3 id="ERR_MANIFEST_TDZ">ERR_MANIFEST_TDZ</h3> <p>An attempt was made to read from a policy manifest, but the manifest initialization has not yet taken place. This is likely a bug in Node.js.</p>  <h3 id="ERR_MANIFEST_UNKNOWN_ONERROR">ERR_MANIFEST_UNKNOWN_ONERROR</h3> <p>A policy manifest was loaded, but had an unknown value for its "onerror" behavior. See the documentation for <a href="../policy/">policy</a> manifests for more information.</p>  <h3 id="ERR_MEMORY_ALLOCATION_FAILED">ERR_MEMORY_ALLOCATION_FAILED</h3> <p>An attempt was made to allocate memory (usually in the C++ layer) but it failed.</p>  <h3 id="ERR_METHOD_NOT_IMPLEMENTED">ERR_METHOD_NOT_IMPLEMENTED</h3> <p>A method is required but not implemented.</p>  <h3 id="ERR_MISSING_ARGS">ERR_MISSING_ARGS</h3> <p>A required argument of a Node.js API was not passed. This is only used for strict compliance with the API specification (which in some cases may accept <code>func(undefined)</code> but not <code>func()</code>). In most native Node.js APIs, <code>func(undefined)</code> and <code>func()</code> are treated identically, and the <a href="#ERR_INVALID_ARG_TYPE"><code>ERR_INVALID_ARG_TYPE</code></a> error code may be used instead.</p>  <h3 id="ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK">ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK</h3> 
<div class="api_stability api_stability_1">
<a href="https://nodejs.org/dist/latest-v12.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 1</a> - Experimental</div>
 <p>An <a href="../esm/">ES Module</a> loader hook specified <code>format: 'dynamic'</code> but did not provide a <code>dynamicInstantiate</code> hook.</p>  <h3 id="ERR_MISSING_MESSAGE_PORT_IN_TRANSFER_LIST">ERR_MISSING_MESSAGE_PORT_IN_TRANSFER_LIST</h3> <p>A <code>MessagePort</code> was found in the object passed to a <code>postMessage()</code> call, but not provided in the <code>transferList</code> for that call.</p>  <h3 id="ERR_MISSING_PASSPHRASE">ERR_MISSING_PASSPHRASE</h3> <p>An attempt was made to read an encrypted key without specifying a passphrase.</p>  <h3 id="ERR_MISSING_PLATFORM_FOR_WORKER">ERR_MISSING_PLATFORM_FOR_WORKER</h3> <p>The V8 platform used by this instance of Node.js does not support creating Workers. This is caused by lack of embedder support for Workers. In particular, this error will not occur with standard builds of Node.js.</p>  <h3 id="ERR_MODULE_NOT_FOUND">ERR_MODULE_NOT_FOUND</h3> 
<div class="api_stability api_stability_1">
<a href="https://nodejs.org/dist/latest-v12.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 1</a> - Experimental</div>
 <p>An <a href="../esm/">ES Module</a> could not be resolved.</p>  <h3 id="ERR_MULTIPLE_CALLBACK">ERR_MULTIPLE_CALLBACK</h3> <p>A callback was called more than once.</p> <p>A callback is almost always meant to only be called once as the query can either be fulfilled or rejected but not both at the same time. The latter would be possible by calling a callback more than once.</p>  <h3 id="ERR_NAPI_CONS_FUNCTION">ERR_NAPI_CONS_FUNCTION</h3> <p>While using <code>N-API</code>, a constructor passed was not a function.</p>  <h3 id="ERR_NAPI_INVALID_DATAVIEW_ARGS">ERR_NAPI_INVALID_DATAVIEW_ARGS</h3> <p>While calling <code>napi_create_dataview()</code>, a given <code>offset</code> was outside the bounds of the dataview or <code>offset + length</code> was larger than a length of given <code>buffer</code>.</p>  <h3 id="ERR_NAPI_INVALID_TYPEDARRAY_ALIGNMENT">ERR_NAPI_INVALID_TYPEDARRAY_ALIGNMENT</h3> <p>While calling <code>napi_create_typedarray()</code>, the provided <code>offset</code> was not a multiple of the element size.</p>  <h3 id="ERR_NAPI_INVALID_TYPEDARRAY_LENGTH">ERR_NAPI_INVALID_TYPEDARRAY_LENGTH</h3> <p>While calling <code>napi_create_typedarray()</code>, <code>(length * size_of_element) + byte_offset</code> was larger than the length of given <code>buffer</code>.</p>  <h3 id="ERR_NAPI_TSFN_CALL_JS">ERR_NAPI_TSFN_CALL_JS</h3> <p>An error occurred while invoking the JavaScript portion of the thread-safe function.</p>  <h3 id="ERR_NAPI_TSFN_GET_UNDEFINED">ERR_NAPI_TSFN_GET_UNDEFINED</h3> <p>An error occurred while attempting to retrieve the JavaScript <code>undefined</code> value.</p>  <h3 id="ERR_NAPI_TSFN_START_IDLE_LOOP">ERR_NAPI_TSFN_START_IDLE_LOOP</h3> <p>On the main thread, values are removed from the queue associated with the thread-safe function in an idle loop. This error indicates that an error has occurred when attempting to start the loop.</p>  <h3 id="ERR_NAPI_TSFN_STOP_IDLE_LOOP">ERR_NAPI_TSFN_STOP_IDLE_LOOP</h3> <p>Once no more items are left in the queue, the idle loop must be suspended. This error indicates that the idle loop has failed to stop.</p>  <h3 id="ERR_NO_CRYPTO">ERR_NO_CRYPTO</h3> <p>An attempt was made to use crypto features while Node.js was not compiled with OpenSSL crypto support.</p>  <h3 id="ERR_NO_ICU">ERR_NO_ICU</h3> <p>An attempt was made to use features that require <a href="../intl/#intl_internationalization_support">ICU</a>, but Node.js was not compiled with ICU support.</p>  <h3 id="ERR_OUT_OF_RANGE">ERR_OUT_OF_RANGE</h3> <p>A given value is out of the accepted range.</p>  <h3 id="ERR_REQUIRE_ESM">ERR_REQUIRE_ESM</h3> 
<div class="api_stability api_stability_1">
<a href="https://nodejs.org/dist/latest-v12.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 1</a> - Experimental</div>
 <p>An attempt was made to <code>require()</code> an <a href="../esm/">ES Module</a>.</p>  <h3 id="ERR_SCRIPT_EXECUTION_INTERRUPTED">ERR_SCRIPT_EXECUTION_INTERRUPTED</h3> <p>Script execution was interrupted by <code>SIGINT</code> (For example, when Ctrl+C was pressed).</p>  <h3 id="ERR_SCRIPT_EXECUTION_TIMEOUT">ERR_SCRIPT_EXECUTION_TIMEOUT</h3> <p>Script execution timed out, possibly due to bugs in the script being executed.</p>  <h3 id="ERR_SERVER_ALREADY_LISTEN">ERR_SERVER_ALREADY_LISTEN</h3> <p>The <a href="../net/#net_server_listen"><code>server.listen()</code></a> method was called while a <code>net.Server</code> was already listening. This applies to all instances of <code>net.Server</code>, including HTTP, HTTPS, and HTTP/2 <code>Server</code> instances.</p>  <h3 id="ERR_SERVER_NOT_RUNNING">ERR_SERVER_NOT_RUNNING</h3> <p>The <a href="../net/#net_server_close_callback"><code>server.close()</code></a> method was called when a <code>net.Server</code> was not running. This applies to all instances of <code>net.Server</code>, including HTTP, HTTPS, and HTTP/2 <code>Server</code> instances.</p>  <h3 id="ERR_SOCKET_ALREADY_BOUND">ERR_SOCKET_ALREADY_BOUND</h3> <p>An attempt was made to bind a socket that has already been bound.</p>  <h3 id="ERR_SOCKET_BAD_BUFFER_SIZE">ERR_SOCKET_BAD_BUFFER_SIZE</h3> <p>An invalid (negative) size was passed for either the <code>recvBufferSize</code> or <code>sendBufferSize</code> options in <a href="../dgram/#dgram_dgram_createsocket_options_callback"><code>dgram.createSocket()</code></a>.</p>  <h3 id="ERR_SOCKET_BAD_PORT">ERR_SOCKET_BAD_PORT</h3> <p>An API function expecting a port &gt;= 0 and &lt; 65536 received an invalid value.</p>  <h3 id="ERR_SOCKET_BAD_TYPE">ERR_SOCKET_BAD_TYPE</h3> <p>An API function expecting a socket type (<code>udp4</code> or <code>udp6</code>) received an invalid value.</p>  <h3 id="ERR_SOCKET_BUFFER_SIZE">ERR_SOCKET_BUFFER_SIZE</h3> <p>While using <a href="../dgram/#dgram_dgram_createsocket_options_callback"><code>dgram.createSocket()</code></a>, the size of the receive or send <code>Buffer</code> could not be determined.</p>  <h3 id="ERR_SOCKET_CANNOT_SEND">ERR_SOCKET_CANNOT_SEND</h3> <p>Data could be sent on a socket.</p>  <h3 id="ERR_SOCKET_CLOSED">ERR_SOCKET_CLOSED</h3> <p>An attempt was made to operate on an already closed socket.</p>  <h3 id="ERR_SOCKET_DGRAM_IS_CONNECTED">ERR_SOCKET_DGRAM_IS_CONNECTED</h3> <p>A <a href="../dgram/#dgram_socket_connect_port_address_callback"><code>dgram.connect()</code></a> call was made on an already connected socket.</p>  <h3 id="ERR_SOCKET_DGRAM_NOT_CONNECTED">ERR_SOCKET_DGRAM_NOT_CONNECTED</h3> <p>A <a href="../dgram/#dgram_socket_disconnect"><code>dgram.disconnect()</code></a> or <a href="../dgram/#dgram_socket_remoteaddress"><code>dgram.remoteAddress()</code></a> call was made on a disconnected socket.</p>  <h3 id="ERR_SOCKET_DGRAM_NOT_RUNNING">ERR_SOCKET_DGRAM_NOT_RUNNING</h3> <p>A call was made and the UDP subsystem was not running.</p>  <h3 id="ERR_SRI_PARSE">ERR_SRI_PARSE</h3> <p>A string was provided for a Subresource Integrity check, but was unable to be parsed. Check the format of integrity attributes by looking at the <a href="https://www.w3.org/TR/SRI/#the-integrity-attribute" target="_blank">Subresource Integrity specification</a>.</p>  <h3 id="ERR_STREAM_CANNOT_PIPE">ERR_STREAM_CANNOT_PIPE</h3> <p>An attempt was made to call <a href="../stream/#stream_readable_pipe_destination_options"><code>stream.pipe()</code></a> on a <a href="../stream/#stream_class_stream_writable"><code>Writable</code></a> stream.</p>  <h3 id="ERR_STREAM_DESTROYED">ERR_STREAM_DESTROYED</h3> <p>A stream method was called that cannot complete because the stream was destroyed using <code>stream.destroy()</code>.</p>  <h3 id="ERR_STREAM_NULL_VALUES">ERR_STREAM_NULL_VALUES</h3> <p>An attempt was made to call <a href="../stream/#stream_writable_write_chunk_encoding_callback"><code>stream.write()</code></a> with a <code>null</code> chunk.</p>  <h3 id="ERR_STREAM_PREMATURE_CLOSE">ERR_STREAM_PREMATURE_CLOSE</h3> <p>An error returned by <code>stream.finished()</code> and <code>stream.pipeline()</code>, when a stream or a pipeline ends non gracefully with no explicit error.</p>  <h3 id="ERR_STREAM_PUSH_AFTER_EOF">ERR_STREAM_PUSH_AFTER_EOF</h3> <p>An attempt was made to call <a href="../stream/#stream_readable_push_chunk_encoding"><code>stream.push()</code></a> after a <code>null</code>(EOF) had been pushed to the stream.</p>  <h3 id="ERR_STREAM_UNSHIFT_AFTER_END_EVENT">ERR_STREAM_UNSHIFT_AFTER_END_EVENT</h3> <p>An attempt was made to call <a href="../stream/#stream_readable_unshift_chunk_encoding"><code>stream.unshift()</code></a> after the <code>'end'</code> event was emitted.</p>  <h3 id="ERR_STREAM_WRAP">ERR_STREAM_WRAP</h3> <p>Prevents an abort if a string decoder was set on the Socket or if the decoder is in <code>objectMode</code>.</p> <pre data-language="js">const Socket = require('net').Socket;
const instance = new Socket();

instance.setEncoding('utf8');
</pre>  <h3 id="ERR_STREAM_WRITE_AFTER_END">ERR_STREAM_WRITE_AFTER_END</h3> <p>An attempt was made to call <a href="../stream/#stream_writable_write_chunk_encoding_callback"><code>stream.write()</code></a> after <code>stream.end()</code> has been called.</p>  <h3 id="ERR_STRING_TOO_LONG">ERR_STRING_TOO_LONG</h3> <p>An attempt has been made to create a string longer than the maximum allowed length.</p>  <h3 id="ERR_SYNTHETIC">ERR_SYNTHETIC</h3> <p>An artificial error object used to capture the call stack for diagnostic reports.</p>  <h3 id="ERR_SYSTEM_ERROR">ERR_SYSTEM_ERROR</h3> <p>An unspecified or non-specific system error has occurred within the Node.js process. The error object will have an <code>err.info</code> object property with additional details.</p>  <h3 id="ERR_TLS_CERT_ALTNAME_INVALID">ERR_TLS_CERT_ALTNAME_INVALID</h3> <p>While using TLS, the hostname/IP of the peer did not match any of the <code>subjectAltNames</code> in its certificate.</p>  <h3 id="ERR_TLS_DH_PARAM_SIZE">ERR_TLS_DH_PARAM_SIZE</h3> <p>While using TLS, the parameter offered for the Diffie-Hellman (<code>DH</code>) key-agreement protocol is too small. By default, the key length must be greater than or equal to 1024 bits to avoid vulnerabilities, even though it is strongly recommended to use 2048 bits or larger for stronger security.</p>  <h3 id="ERR_TLS_HANDSHAKE_TIMEOUT">ERR_TLS_HANDSHAKE_TIMEOUT</h3> <p>A TLS/SSL handshake timed out. In this case, the server must also abort the connection.</p>  <h3 id="ERR_TLS_INVALID_PROTOCOL_METHOD">ERR_TLS_INVALID_PROTOCOL_METHOD</h3> <p>The specified <code>secureProtocol</code> method is invalid. It is either unknown, or disabled because it is insecure.</p>  <h3 id="ERR_TLS_INVALID_PROTOCOL_VERSION">ERR_TLS_INVALID_PROTOCOL_VERSION</h3> <p>Valid TLS protocol versions are <code>'TLSv1'</code>, <code>'TLSv1.1'</code>, or <code>'TLSv1.2'</code>.</p>  <h3 id="ERR_TLS_PROTOCOL_VERSION_CONFLICT">ERR_TLS_PROTOCOL_VERSION_CONFLICT</h3> <p>Attempting to set a TLS protocol <code>minVersion</code> or <code>maxVersion</code> conflicts with an attempt to set the <code>secureProtocol</code> explicitly. Use one mechanism or the other.</p>  <h3 id="ERR_TLS_RENEGOTIATION_DISABLED">ERR_TLS_RENEGOTIATION_DISABLED</h3> <p>An attempt was made to renegotiate TLS on a socket instance with TLS disabled.</p>  <h3 id="ERR_TLS_REQUIRED_SERVER_NAME">ERR_TLS_REQUIRED_SERVER_NAME</h3> <p>While using TLS, the <code>server.addContext()</code> method was called without providing a hostname in the first parameter.</p>  <h3 id="ERR_TLS_SESSION_ATTACK">ERR_TLS_SESSION_ATTACK</h3> <p>An excessive amount of TLS renegotiations is detected, which is a potential vector for denial-of-service attacks.</p>  <h3 id="ERR_TLS_SNI_FROM_SERVER">ERR_TLS_SNI_FROM_SERVER</h3> <p>An attempt was made to issue Server Name Indication from a TLS server-side socket, which is only valid from a client.</p>  <h3 id="ERR_TRACE_EVENTS_CATEGORY_REQUIRED">ERR_TRACE_EVENTS_CATEGORY_REQUIRED</h3> <p>The <code>trace_events.createTracing()</code> method requires at least one trace event category.</p>  <h3 id="ERR_TRACE_EVENTS_UNAVAILABLE">ERR_TRACE_EVENTS_UNAVAILABLE</h3> <p>The <code>trace_events</code> module could not be loaded because Node.js was compiled with the <code>--without-v8-platform</code> flag.</p>  <h3 id="ERR_TRANSFERRING_EXTERNALIZED_SHAREDARRAYBUFFER">ERR_TRANSFERRING_EXTERNALIZED_SHAREDARRAYBUFFER</h3> <p>A <code>SharedArrayBuffer</code> whose memory is not managed by the JavaScript engine or by Node.js was encountered during serialization. Such a <code>SharedArrayBuffer</code> cannot be serialized.</p> <p>This can only happen when native addons create <code>SharedArrayBuffer</code>s in "externalized" mode, or put existing <code>SharedArrayBuffer</code> into externalized mode.</p>  <h3 id="ERR_TRANSFORM_ALREADY_TRANSFORMING">ERR_TRANSFORM_ALREADY_TRANSFORMING</h3> <p>A <code>Transform</code> stream finished while it was still transforming.</p>  <h3 id="ERR_TRANSFORM_WITH_LENGTH_0">ERR_TRANSFORM_WITH_LENGTH_0</h3> <p>A <code>Transform</code> stream finished with data still in the write buffer.</p>  <h3 id="ERR_TTY_INIT_FAILED">ERR_TTY_INIT_FAILED</h3> <p>The initialization of a TTY failed due to a system error.</p>  <h3 id="ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET">ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET</h3> <p><a href="../process/#process_process_setuncaughtexceptioncapturecallback_fn"><code>process.setUncaughtExceptionCaptureCallback()</code></a> was called twice, without first resetting the callback to <code>null</code>.</p> <p>This error is designed to prevent accidentally overwriting a callback registered from another module.</p>  <h3 id="ERR_UNESCAPED_CHARACTERS">ERR_UNESCAPED_CHARACTERS</h3> <p>A string that contained unescaped characters was received.</p>  <h3 id="ERR_UNHANDLED_ERROR">ERR_UNHANDLED_ERROR</h3> <p>An unhandled error occurred (for instance, when an <code>'error'</code> event is emitted by an <a href="../events/#events_class_eventemitter"><code>EventEmitter</code></a> but an <code>'error'</code> handler is not registered).</p>  <h3 id="ERR_UNKNOWN_BUILTIN_MODULE">ERR_UNKNOWN_BUILTIN_MODULE</h3> <p>Used to identify a specific kind of internal Node.js error that should not typically be triggered by user code. Instances of this error point to an internal bug within the Node.js binary itself.</p>  <h3 id="ERR_UNKNOWN_CREDENTIAL">ERR_UNKNOWN_CREDENTIAL</h3> <p>A Unix group or user identifier that does not exist was passed.</p>  <h3 id="ERR_UNKNOWN_ENCODING">ERR_UNKNOWN_ENCODING</h3> <p>An invalid or unknown encoding option was passed to an API.</p>  <h3 id="ERR_UNKNOWN_FILE_EXTENSION">ERR_UNKNOWN_FILE_EXTENSION</h3> 
<div class="api_stability api_stability_1">
<a href="https://nodejs.org/dist/latest-v12.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 1</a> - Experimental</div>
 <p>An attempt was made to load a module with an unknown or unsupported file extension.</p>  <h3 id="ERR_UNKNOWN_MODULE_FORMAT">ERR_UNKNOWN_MODULE_FORMAT</h3> 
<div class="api_stability api_stability_1">
<a href="https://nodejs.org/dist/latest-v12.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 1</a> - Experimental</div>
 <p>An attempt was made to load a module with an unknown or unsupported format.</p>  <h3 id="ERR_UNKNOWN_SIGNAL">ERR_UNKNOWN_SIGNAL</h3> <p>An invalid or unknown process signal was passed to an API expecting a valid signal (such as <a href="../child_process/#child_process_subprocess_kill_signal"><code>subprocess.kill()</code></a>).</p>  <h3 id="ERR_V8BREAKITERATOR">ERR_V8BREAKITERATOR</h3> <p>The V8 <code>BreakIterator</code> API was used but the full ICU data set is not installed.</p>  <h3 id="ERR_VALID_PERFORMANCE_ENTRY_TYPE">ERR_VALID_PERFORMANCE_ENTRY_TYPE</h3> <p>While using the Performance Timing API (<code>perf_hooks</code>), no valid performance entry types were found.</p>  <h3 id="ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING">ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING</h3> <p>A dynamic import callback was not specified.</p>  <h3 id="ERR_VM_MODULE_ALREADY_LINKED">ERR_VM_MODULE_ALREADY_LINKED</h3> <p>The module attempted to be linked is not eligible for linking, because of one of the following reasons:</p> <ul> <li>It has already been linked (<code>linkingStatus</code> is <code>'linked'</code>)</li> <li>It is being linked (<code>linkingStatus</code> is <code>'linking'</code>)</li> <li>Linking has failed for this module (<code>linkingStatus</code> is <code>'errored'</code>)</li> </ul>  <h3 id="ERR_VM_MODULE_DIFFERENT_CONTEXT">ERR_VM_MODULE_DIFFERENT_CONTEXT</h3> <p>The module being returned from the linker function is from a different context than the parent module. Linked modules must share the same context.</p>  <h3 id="ERR_VM_MODULE_LINKING_ERRORED">ERR_VM_MODULE_LINKING_ERRORED</h3> <p>The linker function returned a module for which linking has failed.</p>  <h3 id="ERR_VM_MODULE_NOT_LINKED">ERR_VM_MODULE_NOT_LINKED</h3> <p>The module must be successfully linked before instantiation.</p>  <h3 id="ERR_VM_MODULE_NOT_MODULE">ERR_VM_MODULE_NOT_MODULE</h3> <p>The fulfilled value of a linking promise is not a <code>vm.SourceTextModule</code> object.</p>  <h3 id="ERR_VM_MODULE_STATUS">ERR_VM_MODULE_STATUS</h3> <p>The current module's status does not allow for this operation. The specific meaning of the error depends on the specific function.</p>  <h3 id="ERR_WORKER_INVALID_EXEC_ARGV">ERR_WORKER_INVALID_EXEC_ARGV</h3> <p>The <code>execArgv</code> option passed to the <code>Worker</code> constructor contains invalid flags.</p>  <h3 id="ERR_WORKER_PATH">ERR_WORKER_PATH</h3> <p>The path for the main script of a worker is neither an absolute path nor a relative path starting with <code>./</code> or <code>../</code>.</p>  <h3 id="ERR_WORKER_UNSERIALIZABLE_ERROR">ERR_WORKER_UNSERIALIZABLE_ERROR</h3> <p>All attempts at serializing an uncaught exception from a worker thread failed.</p>  <h3 id="ERR_WORKER_UNSUPPORTED_EXTENSION">ERR_WORKER_UNSUPPORTED_EXTENSION</h3> <p>The pathname used for the main script of a worker has an unknown file extension.</p>  <h3 id="ERR_WORKER_UNSUPPORTED_OPERATION">ERR_WORKER_UNSUPPORTED_OPERATION</h3> <p>The requested functionality is not supported in worker threads.</p>  <h3 id="ERR_ZLIB_INITIALIZATION_FAILED">ERR_ZLIB_INITIALIZATION_FAILED</h3> <p>Creation of a <a href="../zlib/"><code>zlib</code></a> object failed due to incorrect configuration.</p>  <h3 id="errors_hpe_header_overflow">HPE_HEADER_OVERFLOW</h3> <div class="api_metadata"> <details class="changelog"><summary>History</summary> <table> <tbody>
<tr>
<th>Version</th>
<th>Changes</th>
</tr> <tr>
<td>v11.4.0</td> <td><p>Max header size in <code>http_parser</code> was set to 8KB.</p></td>
</tr> </tbody>
</table> </details> </div> <p>Too much HTTP header data was received. In order to protect against malicious or malconfigured clients, if more than 8KB of HTTP header data is received then HTTP parsing will abort without a request or response object being created, and an <code>Error</code> with this code will be emitted.</p>  <h3 id="errors_module_not_found">MODULE_NOT_FOUND</h3> <div class="api_metadata"> <details class="changelog"><summary>History</summary> <table> <tbody>
<tr>
<th>Version</th>
<th>Changes</th>
</tr> <tr>
<td>v12.0.0</td> <td><p>Added <code>requireStack</code> property.</p></td>
</tr> </tbody>
</table> </details> </div> <p>A module file could not be resolved while attempting a <a href="../modules/#modules_require_id"><code>require()</code></a> or <code>import</code> operation.</p> <h2 id="errors_legacy_node_js_error_codes">Legacy Node.js Error Codes</h2> 
<div class="api_stability api_stability_0">
<a href="https://nodejs.org/dist/latest-v12.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 0</a> - Deprecated. These error codes are either inconsistent, or have been removed.</div>
  <h3 id="ERR_CANNOT_TRANSFER_OBJECT">ERR_CANNOT_TRANSFER_OBJECT</h3>  <p>The value passed to <code>postMessage()</code> contained an object that is not supported for transferring.</p>  <h3 id="ERR_CLOSED_MESSAGE_PORT">ERR_CLOSED_MESSAGE_PORT</h3> <div class="api_metadata"> <span>Added in: v10.5.0</span><span>Removed in: v11.12.0</span> </div> <p>There was an attempt to use a <code>MessagePort</code> instance in a closed state, usually after <code>.close()</code> has been called.</p>  <h3 id="ERR_HTTP2_FRAME_ERROR">ERR_HTTP2_FRAME_ERROR</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>Used when a failure occurs sending an individual frame on the HTTP/2 session.</p>  <h3 id="ERR_HTTP2_HEADERS_OBJECT">ERR_HTTP2_HEADERS_OBJECT</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>Used when an HTTP/2 Headers Object is expected.</p>  <h3 id="ERR_HTTP2_HEADER_REQUIRED">ERR_HTTP2_HEADER_REQUIRED</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>Used when a required header is missing in an HTTP/2 message.</p>  <h3 id="ERR_HTTP2_INFO_HEADERS_AFTER_RESPOND">ERR_HTTP2_INFO_HEADERS_AFTER_RESPOND</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>HTTP/2 informational headers must only be sent <em>prior</em> to calling the <code>Http2Stream.prototype.respond()</code> method.</p>  <h3 id="ERR_HTTP2_STREAM_CLOSED">ERR_HTTP2_STREAM_CLOSED</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>Used when an action has been performed on an HTTP/2 Stream that has already been closed.</p>  <h3 id="ERR_HTTP_INVALID_CHAR">ERR_HTTP_INVALID_CHAR</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>Used when an invalid character is found in an HTTP response status message (reason phrase).</p>  <h3 id="ERR_INDEX_OUT_OF_RANGE">ERR_INDEX_OUT_OF_RANGE</h3> <div class="api_metadata"> <span>Added in: v10.0.0</span><span>Removed in: v11.0.0</span> </div> <p>A given index was out of the accepted range (e.g. negative offsets).</p>  <h3 id="ERR_NAPI_CONS_PROTOTYPE_OBJECT">ERR_NAPI_CONS_PROTOTYPE_OBJECT</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>Used by the <code>N-API</code> when <code>Constructor.prototype</code> is not an object.</p>  <h3 id="ERR_NO_LONGER_SUPPORTED">ERR_NO_LONGER_SUPPORTED</h3> <p>A Node.js API was called in an unsupported manner, such as <code>Buffer.write(string, encoding, offset[, length])</code>.</p>  <h3 id="ERR_OUTOFMEMORY">ERR_OUTOFMEMORY</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>Used generically to identify that an operation caused an out of memory condition.</p>  <h3 id="ERR_PARSE_HISTORY_DATA">ERR_PARSE_HISTORY_DATA</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>The <code>repl</code> module was unable to parse data from the REPL history file.</p>  <h3 id="ERR_STDERR_CLOSE">ERR_STDERR_CLOSE</h3> <div class="api_metadata"> <details class="changelog"><summary>History</summary> <table> <tbody>
<tr>
<th>Version</th>
<th>Changes</th>
</tr> <tr>
<td>v10.12.0</td> <td><p>Rather than emitting an error, <code>process.stderr.end()</code> now only closes the stream side but not the underlying resource, making this error obsolete.</p></td>
</tr> <tr>
<td>v10.12.0</td> <td><p><span>Removed in: v10.12.0</span></p></td>
</tr> </tbody>
</table> </details> </div> <p>An attempt was made to close the <code>process.stderr</code> stream. By design, Node.js does not allow <code>stdout</code> or <code>stderr</code> streams to be closed by user code.</p>  <h3 id="ERR_STDOUT_CLOSE">ERR_STDOUT_CLOSE</h3> <div class="api_metadata"> <details class="changelog"><summary>History</summary> <table> <tbody>
<tr>
<th>Version</th>
<th>Changes</th>
</tr> <tr>
<td>v10.12.0</td> <td><p>Rather than emitting an error, <code>process.stderr.end()</code> now only closes the stream side but not the underlying resource, making this error obsolete.</p></td>
</tr> <tr>
<td>v10.12.0</td> <td><p><span>Removed in: v10.12.0</span></p></td>
</tr> </tbody>
</table> </details> </div> <p>An attempt was made to close the <code>process.stdout</code> stream. By design, Node.js does not allow <code>stdout</code> or <code>stderr</code> streams to be closed by user code.</p>  <h3 id="ERR_STREAM_READ_NOT_IMPLEMENTED">ERR_STREAM_READ_NOT_IMPLEMENTED</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>Used when an attempt is made to use a readable stream that has not implemented <a href="../stream/#stream_readable_read_size_1"><code>readable._read()</code></a>.</p>  <h3 id="ERR_TLS_RENEGOTIATION_FAILED">ERR_TLS_RENEGOTIATION_FAILED</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>Used when a TLS renegotiation request has failed in a non-specific way.</p>  <h3 id="ERR_UNKNOWN_BUILTIN_MODULE">ERR_UNKNOWN_BUILTIN_MODULE</h3> <div class="api_metadata"> <span>Added in: v8.0.0</span><span>Removed in: v9.0.0</span> </div> <p>The <code>'ERR_UNKNOWN_BUILTIN_MODULE'</code> error code is used to identify a specific kind of internal Node.js error that should not typically be triggered by user code. Instances of this error point to an internal bug within the Node.js binary itself.</p>  <h3 id="ERR_UNKNOWN_STDIN_TYPE">ERR_UNKNOWN_STDIN_TYPE</h3> <div class="api_metadata"> <span>Added in: v8.0.0</span><span>Removed in: v11.7.0</span> </div> <p>An attempt was made to launch a Node.js process with an unknown <code>stdin</code> file type. This error is usually an indication of a bug within Node.js itself, although it is possible for user code to trigger it.</p>  <h3 id="ERR_UNKNOWN_STREAM_TYPE">ERR_UNKNOWN_STREAM_TYPE</h3> <div class="api_metadata"> <span>Added in: v8.0.0</span><span>Removed in: v11.7.0</span> </div> <p>An attempt was made to launch a Node.js process with an unknown <code>stdout</code> or <code>stderr</code> file type. This error is usually an indication of a bug within Node.js itself, although it is possible for user code to trigger it.</p>  <h3 id="ERR_VALUE_OUT_OF_RANGE">ERR_VALUE_OUT_OF_RANGE</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>Used when a given value is out of the accepted range.</p>  <h3 id="ERR_ZLIB_BINDING_CLOSED">ERR_ZLIB_BINDING_CLOSED</h3> <div class="api_metadata"> <span>Added in: v9.0.0</span><span>Removed in: v10.0.0</span> </div> <p>Used when an attempt is made to use a <code>zlib</code> object after it has already been closed.</p> <h3 id="errors_other_error_codes">Other error codes</h3> <p>These errors have never been released, but had been present on master between releases.</p>  <h4 id="ERR_ENTRY_TYPE_MISMATCH">ERR_ENTRY_TYPE_MISMATCH</h4> 
<div class="api_stability api_stability_1">
<a href="https://nodejs.org/dist/latest-v12.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 1</a> - Experimental</div>
 <p>The <code>--entry-type=commonjs</code> flag was used to attempt to execute an <code>.mjs</code> file or a <code>.js</code> file where the nearest parent <code>package.json</code> contains <code>"type": "module"</code>; or the <code>--entry-type=module</code> flag was used to attempt to execute a <code>.cjs</code> file or a <code>.js</code> file where the nearest parent <code>package.json</code> either lacks a <code>"type"</code> field or contains <code>"type": "commonjs"</code>.</p>  <h4 id="ERR_FS_WATCHER_ALREADY_STARTED">ERR_FS_WATCHER_ALREADY_STARTED</h4> <p>An attempt was made to start a watcher returned by <code>fs.watch()</code> that has already been started.</p>  <h4 id="ERR_FS_WATCHER_NOT_STARTED">ERR_FS_WATCHER_NOT_STARTED</h4> <p>An attempt was made to initiate operations on a watcher returned by <code>fs.watch()</code> that has not yet been started.</p>  <h4 id="ERR_HTTP2_ALREADY_SHUTDOWN">ERR_HTTP2_ALREADY_SHUTDOWN</h4> <p>Occurs with multiple attempts to shutdown an HTTP/2 session.</p>  <h4 id="ERR_HTTP2_ERROR">ERR_HTTP2_ERROR</h4> <p>A non-specific HTTP/2 error has occurred.</p>  <h4 id="ERR_INVALID_REPL_HISTORY">ERR_INVALID_REPL_HISTORY</h4> <p>Used in the <code>repl</code> in case the old history file is used and an error occurred while trying to read and parse it.</p>  <h4 id="ERR_INVALID_REPL_TYPE">ERR_INVALID_REPL_TYPE</h4> 
<div class="api_stability api_stability_1">
<a href="https://nodejs.org/dist/latest-v12.x/docs/api/documentation.html#documentation_stability_index" target="_blank">Stability: 1</a> - Experimental</div>
 <p>The <code>--entry-type=...</code> flag is not compatible with the Node.js REPL.</p>  <h4 id="ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK">ERR_MISSING_DYNAMIC_INSTANTIATE_HOOK</h4> <p>Used when an <a href="../esm/">ES Module</a> loader hook specifies <code>format: 'dynamic'</code> but does not provide a <code>dynamicInstantiate</code> hook.</p>  <h4 id="ERR_STREAM_HAS_STRINGDECODER">ERR_STREAM_HAS_STRINGDECODER</h4> <p>Used to prevent an abort if a string decoder was set on the Socket.</p> <pre data-language="js">const Socket = require('net').Socket;
const instance = new Socket();

instance.setEncoding('utf8');
</pre>  <h4 id="ERR_STRING_TOO_LARGE">ERR_STRING_TOO_LARGE</h4> <p>An attempt has been made to create a string larger than the maximum allowed size.</p>  <h4 id="ERR_TTY_WRITABLE_NOT_READABLE">ERR_TTY_WRITABLE_NOT_READABLE</h4> <p>This <code>Error</code> is thrown when a read is attempted on a TTY <code>WriteStream</code>, such as <code>process.stdout.on('data')</code>.</p>
<div class="_attribution">
  <p class="_attribution-p">
    © Joyent, Inc. and other Node contributors<br>Licensed under the MIT License.<br>Node.js is a trademark of Joyent, Inc. and is used with its permission.<br>We are not endorsed by or affiliated with Joyent.<br>
    <a href="https://nodejs.org/dist/latest-v12.x/docs/api/errors.html" class="_attribution-link" target="_blank">https://nodejs.org/dist/latest-v12.x/docs/api/errors.html</a>
  </p>
</div>

				
			</div>
			<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
</amp-auto-ads>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
