
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Errors - Node.js 6 LTS - W3cubDocs</title>
  
  <meta name="description" content=" Applications running in Node.js will generally experience four categories of errors&#58; ">
  <meta name="keywords" content="errors, -, node, js, lts, node~6_lts">
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="http://docs.w3cub.com/node~6_lts/errors/">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" integrity="sha256-6/DH7X+2hvUPElJfGsvzm+tgIpmM9zjbYxnpsr6gR1A=" crossorigin="anonymous" href="/assets/application-ebf0c7ed7fb686f50f12525f1acbf39beb6022998cf738db6319e9b2bea04750.css">
  <script type="text/javascript" src="/assets/application-db285287b40ed28fac520fcfd75d7d874692b647b5b5e05968c741dda5de4148.js" integrity="sha256-2yhSh7QO0o+sUg/P1119h0aStke1teBZaMdB3aXeQUg=" crossorigin="anonymous"></script>
  <script src="/json/node~6_lts.js"></script>
  
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-71174418-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-2572770204602497",
            enable_page_level_ads: true
        });
  </script>
  <script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body>
	<div class="_app">
	<header class="_header">
  
  <form class="_search">
    <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
    <a class="_search-clear"></a>
    <div class="_search-tag"></div>
  </form>
  
  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/node~6_lts/" class="_nav-link" title="" style="margin-left:0;">Node.js 6 LTS</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		<div class="_list">
			
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="link"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _node">
				
				
<h1 id="errors_errors">Errors</h1>   <p>Applications running in Node.js will generally experience four categories of errors:</p> <ul> <li>Standard JavaScript errors such as:<ul> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError" class="type" target="_blank">&lt;EvalError&gt;</a> : thrown when a call to <code>eval()</code> fails.</li> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError" class="type" target="_blank">&lt;SyntaxError&gt;</a> : thrown in response to improper JavaScript language syntax.</li> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError" class="type" target="_blank">&lt;RangeError&gt;</a> : thrown when a value is not within an expected range</li> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError" class="type" target="_blank">&lt;ReferenceError&gt;</a> : thrown when using undefined variables</li> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError" class="type" target="_blank">&lt;TypeError&gt;</a> : thrown when passing arguments of the wrong type</li> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError" class="type" target="_blank">&lt;URIError&gt;</a> : thrown when a global URI handling function is misused.</li> </ul> </li> <li>System errors triggered by underlying operating system constraints such as attempting to open a file that does not exist, attempting to send data over a closed socket, etc;</li> <li>And User-specified errors triggered by application code.</li> <li>Assertion Errors are a special class of error that can be triggered whenever Node.js detects an exceptional logic violation that should never occur. These are raised typically by the <code>assert</code> module.</li> </ul> <p>All JavaScript and System errors raised by Node.js inherit from, or are instances of, the standard JavaScript <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error" class="type" target="_blank">&lt;Error&gt;</a> class and are guaranteed to provide <em>at least</em> the properties available on that class.</p> <h2 id="errors_error_propagation_and_interception">Error Propagation and Interception</h2>  <p>Node.js supports several mechanisms for propagating and handling errors that occur while an application is running. How these errors are reported and handled depends entirely on the type of Error and the style of the API that is called.</p> <p>All JavaScript errors are handled as exceptions that <em>immediately</em> generate and throw an error using the standard JavaScript <code>throw</code> mechanism. These are handled using the <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch" target="_blank"><code>try / catch</code> construct</a> provided by the JavaScript language.</p> <pre data-language="js">// Throws with a ReferenceError because z is undefined
try {
  const m = 1;
  const n = m + z;
} catch (err) {
  // Handle the error here.
}
</pre> <p>Any use of the JavaScript <code>throw</code> mechanism will raise an exception that <em>must</em> be handled using <code>try / catch</code> or the Node.js process will exit immediately.</p> <p>With few exceptions, <em>Synchronous</em> APIs (any blocking method that does not accept a <code>callback</code> function, such as <a href="../fs/#fs_fs_readfilesync_file_options"><code>fs.readFileSync</code></a>), will use <code>throw</code> to report errors.</p> <p>Errors that occur within <em>Asynchronous APIs</em> may be reported in multiple ways:</p> <ul> <li>Most asynchronous methods that accept a <code>callback</code> function will accept an <code>Error</code> object passed as the first argument to that function. If that first argument is not <code>null</code> and is an instance of <code>Error</code>, then an error occurred that should be handled.</li> </ul>  <pre data-language="js">  const fs = require('fs');
  fs.readFile('a file that does not exist', (err, data) =&gt; {
    if (err) {
      console.error('There was an error reading the file!', err);
      return;
    }
    // Otherwise handle the data
  });
</pre> <ul> <li>
<p>When an asynchronous method is called on an object that is an <code>EventEmitter</code>, errors can be routed to that object's <code>'error'</code> event.</p> <pre data-language="js">const net = require('net');
const connection = net.connect('localhost');

// Adding an 'error' event handler to a stream:
connection.on('error', (err) =&gt; {
  // If the connection is reset by the server, or if it can't
  // connect at all, or on any sort of error encountered by
  // the connection, the error will be sent here.
  console.error(err);
});

connection.pipe(process.stdout);
</pre> </li> <li>
<p>A handful of typically asynchronous methods in the Node.js API may still use the <code>throw</code> mechanism to raise exceptions that must be handled using <code>try / catch</code>. There is no comprehensive list of such methods; please refer to the documentation of each method to determine the appropriate error handling mechanism required.</p> </li> </ul> <p>The use of the <code>'error'</code> event mechanism is most common for <a href="../stream/">stream-based</a> and <a href="../events/#events_class_eventemitter">event emitter-based</a> APIs, which themselves represent a series of asynchronous operations over time (as opposed to a single operation that may pass or fail).</p> <p>For <em>all</em> <code>EventEmitter</code> objects, if an <code>'error'</code> event handler is not provided, the error will be thrown, causing the Node.js process to report an unhandled exception and crash unless either: The <a href="../domain/"><code>domain</code></a> module is used appropriately or a handler has been registered for the <a href="../process/#process_event_uncaughtexception"><code>process.on('uncaughtException')</code></a> event.</p> <pre data-language="js">const EventEmitter = require('events');
const ee = new EventEmitter();

setImmediate(() =&gt; {
  // This will crash the process because no 'error' event
  // handler has been added.
  ee.emit('error', new Error('This will crash'));
});
</pre> <p>Errors generated in this way <em>cannot</em> be intercepted using <code>try / catch</code> as they are thrown <em>after</em> the calling code has already exited.</p> <p>Developers must refer to the documentation for each method to determine exactly how errors raised by those methods are propagated.</p> <h3 id="errors_node_js_style_callbacks">Node.js style callbacks</h3>  <p>Most asynchronous methods exposed by the Node.js core API follow an idiomatic pattern referred to as a "Node.js style callback". With this pattern, a callback function is passed to the method as an argument. When the operation either completes or an error is raised, the callback function is called with the Error object (if any) passed as the first argument. If no error was raised, the first argument will be passed as <code>null</code>.</p> <pre data-language="js">const fs = require('fs');

function nodeStyleCallback(err, data) {
  if (err) {
    console.error('There was an error', err);
    return;
  }
  console.log(data);
}

fs.readFile('/some/file/that/does-not-exist', nodeStyleCallback);
fs.readFile('/some/file/that/does-exist', nodeStyleCallback);
</pre> <p>The JavaScript <code>try / catch</code> mechanism <strong>cannot</strong> be used to intercept errors generated by asynchronous APIs. A common mistake for beginners is to try to use <code>throw</code> inside a Node.js style callback:</p> <pre data-language="js">// THIS WILL NOT WORK:
const fs = require('fs');

try {
  fs.readFile('/some/file/that/does-not-exist', (err, data) =&gt; {
    // mistaken assumption: throwing here...
    if (err) {
      throw err;
    }
  });
} catch (err) {
  // This will not catch the throw!
  console.error(err);
}
</pre> <p>This will not work because the callback function passed to <code>fs.readFile()</code> is called asynchronously. By the time the callback has been called, the surrounding code (including the <code>try { } catch (err) { }</code> block will have already exited. Throwing an error inside the callback <strong>can crash the Node.js process</strong> in most cases. If <a href="../domain/">domains</a> are enabled, or a handler has been registered with <code>process.on('uncaughtException')</code>, such errors can be intercepted.</p> <h2 id="errors_class_error">Class: Error</h2>  <p>A generic JavaScript <code>Error</code> object that does not denote any specific circumstance of why the error occurred. <code>Error</code> objects capture a "stack trace" detailing the point in the code at which the <code>Error</code> was instantiated, and may provide a text description of the error.</p> <p>All errors generated by Node.js, including all System and JavaScript errors, will either be instances of, or inherit from, the <code>Error</code> class.</p> <h3 id="errors_new_error_message">new Error(message)</h3> <div class="signature">
<ul> <li>
<code>message</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a>
</li> </ul> </div>
<p>Creates a new <code>Error</code> object and sets the <code>error.message</code> property to the provided text message. If an object is passed as <code>message</code>, the text message is generated by calling <code>message.toString()</code>. The <code>error.stack</code> property will represent the point in the code at which <code>new Error()</code> was called. Stack traces are dependent on <a href="https://github.com/v8/v8/wiki/Stack-Trace-API" target="_blank">V8's stack trace API</a>. Stack traces extend only to either (a) the beginning of <em>synchronous code execution</em>, or (b) the number of frames given by the property <code>Error.stackTraceLimit</code>, whichever is smaller.</p> <h3 id="errors_error_capturestacktrace_targetobject_constructoropt">Error.captureStackTrace(targetObject[, constructorOpt])</h3> <div class="signature">
<ul> <li>
<code>targetObject</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object" class="type" target="_blank">&lt;Object&gt;</a>
</li> <li>
<code>constructorOpt</code> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function" class="type" target="_blank">&lt;Function&gt;</a>
</li> </ul> </div>
<p>Creates a <code>.stack</code> property on <code>targetObject</code>, which when accessed returns a string representing the location in the code at which <code>Error.captureStackTrace()</code> was called.</p> <pre data-language="js">const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // similar to `new Error().stack`
</pre> <p>The first line of the trace, instead of being prefixed with <code>ErrorType:
message</code>, will be the result of calling <code>targetObject.toString()</code>.</p> <p>The optional <code>constructorOpt</code> argument accepts a function. If given, all frames above <code>constructorOpt</code>, including <code>constructorOpt</code>, will be omitted from the generated stack trace.</p> <p>The <code>constructorOpt</code> argument is useful for hiding implementation details of error generation from an end user. For instance:</p> <pre data-language="js">function MyError() {
  Error.captureStackTrace(this, MyError);
}

// Without passing MyError to captureStackTrace, the MyError
// frame would show up in the .stack property. By passing
// the constructor, we omit that frame, and retain all frames below it.
new MyError().stack;
</pre> <h3 id="errors_error_stacktracelimit">Error.stackTraceLimit</h3> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type" target="_blank">&lt;number&gt;</a></li> </ul> </div>
<p>The <code>Error.stackTraceLimit</code> property specifies the number of stack frames collected by a stack trace (whether generated by <code>new Error().stack</code> or <code>Error.captureStackTrace(obj)</code>).</p> <p>The default value is <code>10</code> but may be set to any valid JavaScript number. Changes will affect any stack trace captured <em>after</em> the value has been changed.</p> <p>If set to a non-number value, or set to a negative number, stack traces will not capture any frames.</p> <h3 id="errors_error_message">error.message</h3> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>The <code>error.message</code> property is the string description of the error as set by calling <code>new Error(message)</code>. The <code>message</code> passed to the constructor will also appear in the first line of the stack trace of the <code>Error</code>, however changing this property after the <code>Error</code> object is created <em>may not</em> change the first line of the stack trace (for example, when <code>error.stack</code> is read before this property is changed).</p> <pre data-language="js">const err = new Error('The message');
console.error(err.message);
// Prints: The message
</pre> <h3 id="errors_error_stack">error.stack</h3> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>The <code>error.stack</code> property is a string describing the point in the code at which the <code>Error</code> was instantiated.</p> <p>For example:</p> <pre data-language="txt">Error: Things keep happening!
   at /home/gbusey/file.js:525:2
   at Frobnicator.refrobulate (/home/gbusey/business-logic.js:424:21)
   at Actor.&lt;anonymous&gt; (/home/gbusey/actors.js:400:8)
   at increaseSynergy (/home/gbusey/actors.js:701:6)
</pre> <p>The first line is formatted as <code>&lt;error class name&gt;: &lt;error message&gt;</code>, and is followed by a series of stack frames (each line beginning with "at "). Each frame describes a call site within the code that lead to the error being generated. V8 attempts to display a name for each function (by variable name, function name, or object method name), but occasionally it will not be able to find a suitable name. If V8 cannot determine a name for the function, only location information will be displayed for that frame. Otherwise, the determined function name will be displayed with location information appended in parentheses.</p> <p>It is important to note that frames are <strong>only</strong> generated for JavaScript functions. If, for example, execution synchronously passes through a C++ addon function called <code>cheetahify</code>, which itself calls a JavaScript function, the frame representing the <code>cheetahify</code> call will <strong>not</strong> be present in the stack traces:</p> <pre data-language="js">const cheetahify = require('./native-binding.node');

function makeFaster() {
  // cheetahify *synchronously* calls speedy.
  cheetahify(function speedy() {
    throw new Error('oh no!');
  });
}

makeFaster(); // will throw:
// /home/gbusey/file.js:6
//     throw new Error('oh no!');
//           ^
// Error: oh no!
//     at speedy (/home/gbusey/file.js:6:11)
//     at makeFaster (/home/gbusey/file.js:5:3)
//     at Object.&lt;anonymous&gt; (/home/gbusey/file.js:10:1)
//     at Module._compile (module.js:456:26)
//     at Object.Module._extensions..js (module.js:474:10)
//     at Module.load (module.js:356:32)
//     at Function.Module._load (module.js:312:12)
//     at Function.Module.runMain (module.js:497:10)
//     at startup (node.js:119:16)
//     at node.js:906:3
</pre> <p>The location information will be one of:</p> <ul> <li>
<code>native</code>, if the frame represents a call internal to V8 (as in <code>[].forEach</code>).</li> <li>
<code>plain-filename.js:line:column</code>, if the frame represents a call internal to Node.js.</li> <li>
<code>/absolute/path/to/file.js:line:column</code>, if the frame represents a call in a user program, or its dependencies.</li> </ul> <p>The string representing the stack trace is lazily generated when the <code>error.stack</code> property is <strong>accessed</strong>.</p> <p>The number of frames captured by the stack trace is bounded by the smaller of <code>Error.stackTraceLimit</code> or the number of available frames on the current event loop tick.</p> <p>System-level errors are generated as augmented <code>Error</code> instances, which are detailed <a href="#errors_system_errors">here</a>.</p> <h2 id="errors_class_rangeerror">Class: RangeError</h2> <p>A subclass of <code>Error</code> that indicates that a provided argument was not within the set or range of acceptable values for a function; whether that is a numeric range, or outside the set of options for a given function parameter.</p> <p>For example:</p> <pre data-language="js">require('net').connect(-1);
// throws "RangeError: "port" option should be &gt;= 0 and &lt; 65536: -1"
</pre> <p>Node.js will generate and throw <code>RangeError</code> instances <em>immediately</em> as a form of argument validation.</p> <h2 id="errors_class_referenceerror">Class: ReferenceError</h2> <p>A subclass of <code>Error</code> that indicates that an attempt is being made to access a variable that is not defined. Such errors commonly indicate typos in code, or an otherwise broken program.</p> <p>While client code may generate and propagate these errors, in practice, only V8 will do so.</p> <pre data-language="js">doesNotExist;
// throws ReferenceError, doesNotExist is not a variable in this program.
</pre> <p>Unless an application is dynamically generating and running code, <code>ReferenceError</code> instances should always be considered a bug in the code or its dependencies.</p> <h2 id="errors_class_syntaxerror">Class: SyntaxError</h2> <p>A subclass of <code>Error</code> that indicates that a program is not valid JavaScript. These errors may only be generated and propagated as a result of code evaluation. Code evaluation may happen as a result of <code>eval</code>, <code>Function</code>, <code>require</code>, or <a href="../vm/">vm</a>. These errors are almost always indicative of a broken program.</p> <pre data-language="js">try {
  require('vm').runInThisContext('binary ! isNotOk');
} catch (err) {
  // err will be a SyntaxError
}
</pre> <p><code>SyntaxError</code> instances are unrecoverable in the context that created them – they may only be caught by other contexts.</p> <h2 id="errors_class_typeerror">Class: TypeError</h2> <p>A subclass of <code>Error</code> that indicates that a provided argument is not an allowable type. For example, passing a function to a parameter which expects a string would be considered a TypeError.</p> <pre data-language="js">require('url').parse(() =&gt; { });
// throws TypeError, since it expected a string
</pre> <p>Node.js will generate and throw <code>TypeError</code> instances <em>immediately</em> as a form of argument validation.</p> <h2 id="errors_exceptions_vs_errors">Exceptions vs. Errors</h2>  <p>A JavaScript exception is a value that is thrown as a result of an invalid operation or as the target of a <code>throw</code> statement. While it is not required that these values are instances of <code>Error</code> or classes which inherit from <code>Error</code>, all exceptions thrown by Node.js or the JavaScript runtime <em>will</em> be instances of Error.</p> <p>Some exceptions are <em>unrecoverable</em> at the JavaScript layer. Such exceptions will <em>always</em> cause the Node.js process to crash. Examples include <code>assert()</code> checks or <code>abort()</code> calls in the C++ layer.</p> <h2 id="errors_system_errors">System Errors</h2> <p>System errors are generated when exceptions occur within the program's runtime environment. Typically, these are operational errors that occur when an application violates an operating system constraint such as attempting to read a file that does not exist or when the user does not have sufficient permissions.</p> <p>System errors are typically generated at the syscall level: an exhaustive list of error codes and their meanings is available by running <code>man 2 intro</code> or <code>man 3 errno</code> on most Unices; or <a href="http://man7.org/linux/man-pages/man3/errno.3.html" target="_blank">online</a>.</p> <p>In Node.js, system errors are represented as augmented <code>Error</code> objects with added properties.</p> <h3 id="errors_class_system_error">Class: System Error</h3> <h4 id="errors_error_code">error.code</h4> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>The <code>error.code</code> property is a string representing the error code, which is always <code>E</code> followed by a sequence of capital letters.</p> <h4 id="errors_error_errno">error.errno</h4> <div class="signature">
<ul> <li>
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a> | <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type" target="_blank">&lt;number&gt;</a>
</li> </ul> </div>
<p>The <code>error.errno</code> property is a number or a string. The number is a <strong>negative</strong> value which corresponds to the error code defined in <a href="http://docs.libuv.org/en/v1.x/errors.html" target="_blank"><code>libuv Error handling</code></a>. See uv-errno.h header file (<code>deps/uv/include/uv-errno.h</code> in the Node.js source tree) for details. In case of a string, it is the same as <code>error.code</code>.</p> <h4 id="errors_error_syscall">error.syscall</h4> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>The <code>error.syscall</code> property is a string describing the <a href="http://man7.org/linux/man-pages/man2/syscall.2.html" target="_blank">syscall</a> that failed.</p> <h4 id="errors_error_path">error.path</h4> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>When present (e.g. in <code>fs</code> or <code>child_process</code>), the <code>error.path</code> property is a string containing a relevant invalid pathname.</p> <h4 id="errors_error_address">error.address</h4> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type" class="type" target="_blank">&lt;string&gt;</a></li> </ul> </div>
<p>When present (e.g. in <code>net</code> or <code>dgram</code>), the <code>error.address</code> property is a string describing the address to which the connection failed.</p> <h4 id="errors_error_port">error.port</h4> <div class="signature">
<ul> <li><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type" class="type" target="_blank">&lt;number&gt;</a></li> </ul> </div>
<p>When present (e.g. in <code>net</code> or <code>dgram</code>), the <code>error.port</code> property is a number representing the connection's port that is not available.</p> <h3 id="errors_common_system_errors">Common System Errors</h3> <p>This list is <strong>not exhaustive</strong>, but enumerates many of the common system errors encountered when writing a Node.js program. An exhaustive list may be found <a href="http://man7.org/linux/man-pages/man3/errno.3.html" target="_blank">here</a>.</p> <ul> <li>
<p><code>EACCES</code> (Permission denied): An attempt was made to access a file in a way forbidden by its file access permissions.</p> </li> <li>
<p><code>EADDRINUSE</code> (Address already in use): An attempt to bind a server (<a href="../net/"><code>net</code></a>, <a href="http" target="_blank"><code>http</code></a>, or <a href="https" target="_blank"><code>https</code></a>) to a local address failed due to another server on the local system already occupying that address.</p> </li> <li>
<p><code>ECONNREFUSED</code> (Connection refused): No connection could be made because the target machine actively refused it. This usually results from trying to connect to a service that is inactive on the foreign host.</p> </li> <li>
<p><code>ECONNRESET</code> (Connection reset by peer): A connection was forcibly closed by a peer. This normally results from a loss of the connection on the remote socket due to a timeout or reboot. Commonly encountered via the <a href="http" target="_blank"><code>http</code></a> and <a href="../net/"><code>net</code></a> modules.</p> </li> <li>
<p><code>EEXIST</code> (File exists): An existing file was the target of an operation that required that the target not exist.</p> </li> <li>
<p><code>EISDIR</code> (Is a directory): An operation expected a file, but the given pathname was a directory.</p> </li> <li>
<p><code>EMFILE</code> (Too many open files in system): Maximum number of <a href="https://en.wikipedia.org/wiki/File_descriptor" target="_blank">file descriptors</a> allowable on the system has been reached, and requests for another descriptor cannot be fulfilled until at least one has been closed. This is encountered when opening many files at once in parallel, especially on systems (in particular, macOS) where there is a low file descriptor limit for processes. To remedy a low limit, run <code>ulimit -n 2048</code> in the same shell that will run the Node.js process.</p> </li> <li>
<p><code>ENOENT</code> (No such file or directory): Commonly raised by <a href="../fs/"><code>fs</code></a> operations to indicate that a component of the specified pathname does not exist — no entity (file or directory) could be found by the given path.</p> </li> <li>
<p><code>ENOTDIR</code> (Not a directory): A component of the given pathname existed, but was not a directory as expected. Commonly raised by <a href="../fs/#fs_fs_readdir_path_options_callback"><code>fs.readdir</code></a>.</p> </li> <li>
<p><code>ENOTEMPTY</code> (Directory not empty): A directory with entries was the target of an operation that requires an empty directory — usually <a href="../fs/#fs_fs_unlink_path_callback"><code>fs.unlink</code></a>.</p> </li> <li>
<p><code>EPERM</code> (Operation not permitted): An attempt was made to perform an operation that requires elevated privileges.</p> </li> <li>
<p><code>EPIPE</code> (Broken pipe): A write on a pipe, socket, or FIFO for which there is no process to read the data. Commonly encountered at the <a href="../net/"><code>net</code></a> and <a href="http" target="_blank"><code>http</code></a> layers, indicative that the remote side of the stream being written to has been closed.</p> </li> <li>
<p><code>ETIMEDOUT</code> (Operation timed out): A connect or send request failed because the connected party did not properly respond after a period of time. Usually encountered by <a href="http" target="_blank"><code>http</code></a> or <a href="../net/"><code>net</code></a> — often a sign that a <code>socket.end()</code> was not properly called.</p> </li> </ul>
<div class="_attribution">
  <p class="_attribution-p">
    © Joyent, Inc. and other Node contributors<br>Licensed under the MIT License.<br>Node.js is a trademark of Joyent, Inc. and is used with its permission.<br>We are not endorsed by or affiliated with Joyent.<br>
    <a href="https://nodejs.org/dist/latest-v6.x/docs/api/errors.html" class="_attribution-link" target="_blank">https://nodejs.org/dist/latest-v6.x/docs/api/errors.html</a>
  </p>
</div>

				
			</div>
			<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
</amp-auto-ads>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
